CallMD/src/objects/Allergies__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Allergies</relationshipLabel>
        <relationshipName>Allergies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allergies</label>
    <nameField>
        <label>Allergies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allergies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_AllergiesExt.cls
public class CallMD_AllergiesExt {

    Public Allergies__c a{get;set;}
    Private String MemberID=ApexPages.CurrentPage().getParameters().get('mid');

    public CallMD_AllergiesExt(ApexPages.StandardController controller) {
       a=(Allergies__c)controller.getRecord();
    }
    
    Public PageReference p;
    Public PageReference Save(){
       a.Member__c=MemberID;
       insert a;
       p=new PageReference('/apex/CallMD_Member');
       p.getParameters().put('id',MemberID);
       p.getParameters().put('mode','e');
       return p;
    }
    
    Public PageReference Cancel(){
    
       p=new PageReference('/apex/CallMD_Member');
       p.getParameters().put('id',MemberID);
       p.getParameters().put('mode','e');
       return p;
    
    }

}