CallMD/src/objects/Allergies__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Allergies</relationshipLabel>
        <relationshipName>Allergies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reaction__c</fullName>
        <label>Reaction</label>
        <type>TextArea</type>
    </fields>
    <label>Allergies</label>
    <nameField>
        <label>Allergies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allergies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Medical_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Medical Conditions</relationshipLabel>
        <relationshipName>Medical_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medical Conditions</label>
    <nameField>
        <label>Medical Conditions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Medications__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dosage_Units__c</fullName>
        <label>Dosage Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>mg</fullName>
                </value>
                <value>
                    <fullName>mcg</fullName>
                </value>
                <value>
                    <fullName>drops</fullName>
                </value>
                <value>
                    <fullName>units</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dosage__c</fullName>
        <label>Dosage</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_often__c</fullName>
        <label>How often</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Medications</relationshipLabel>
        <relationshipName>Medications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medications</label>
    <nameField>
        <label>Medications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Surgeries__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Surgeries</relationshipLabel>
        <relationshipName>Surgeries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Surgeries</label>
    <nameField>
        <label>Surgeries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgeries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_MemberMedicalCondCtrl.cls
public class CallMD_MemberMedicalCondCtrl {
    
    
    //Public Boolean isCreated{get;set;}
    public string MemberId{get{
        
     return ApexPages.currentPage().getParameters().get('id');   
    }set;}
    
    Public List<Medical_Conditions__c> getMedicalCondList(){
        List<Medical_Conditions__c> medicalCondition=[SELECT id,Name,Current__c,Comments__c 
                                                             FROM Medical_Conditions__c
                                                             WHERE Member__c=:MemberId];
        return medicalCondition;  
    }
    
    Public List<Allergies__c> getAllergiesList(){
        List<Allergies__c> allergies=[SELECT id,Name,Reaction__c  
                                             FROM Allergies__c
                                             WHERE Member__c=:MemberId]; 
        return allergies;   
    }
    
    Public List<Surgeries__c> getSurgeriesList(){  
        List<Surgeries__c> surgeries=[SELECT id,Name,Date__c,Comments__c 
                                            FROM Surgeries__c
                                            WHERE Member__c=:MemberId];
        return surgeries;   
    }
    
    Public List<Medications__c> getMedicationList(){ 
       List<Medications__c> medication=[SELECT id,Name,Current__c,Dosage__c,Dosage_units__c,How_often__c
                                               FROM Medications__c
                                               WHERE Member__c=:MemberId];  
       return medication;
        
    }    
}