CallMD/src/objects/Chief_Complaint_Symptoms__c.object
<CustomObject>
    <label>Chief Complaint Symptoms</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chief Complaint Symptoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Board_Cent__c</fullName>
        <label>Board Cent</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address Line1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR(TODAY()) - YEAR(DateofBirth__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateofBirth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CallBack_Number__c</fullName>
        <label>CallBack Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CallBack_Time__c</fullName>
        <label>CallBack Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consulation_Remarks__c</fullName>
        <label>Consulation Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consultation_Type__c</fullName>
        <label>Consultation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone consultation</fullName>
                </value>
                <value>
                    <fullName>Video Consultation</fullName>
                </value>
                <value>
                    <fullName>Chat Consultation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Time_of_consultation__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date &amp; Time of consultation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DoctorC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Open Consultation</relationshipLabel>
        <relationshipName>Open_Consultation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor_Consultation_Remark__c</fullName>
        <label>Doctor Consultation Remark</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impression_Diagnosis__c</fullName>
        <label>Impression / Diagnosis</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <label>Initiated By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meds_Prescribed_During_Consultation__c</fullName>
        <label>Meds Prescribed During Consultation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pharmacy_Name_Phone__c</fullName>
        <label>Pharmacy Name + Phone:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pharmacy_Verifier__c</fullName>
        <label>Pharmacy Verifier:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Problem_History__c</fullName>
        <label>Patient Complaint</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Problem_History_cs__c</fullName>
        <label>Problem / History:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RX_Status__c</fullName>
        <label>RX Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prescribed Rx Medication</fullName>
                </value>
                <value>
                    <fullName>Prescribed Compound Medication</fullName>
                </value>
                <value>
                    <fullName>No Rx or Compound Medication Prescribed</fullName>
                </value>
                <value>
                    <fullName>Patient Unavailable for Consultation</fullName>
                </value>
                <value>
                    <fullName>Doctor Unavailable for Consultation</fullName>
                </value>
                <value>
                    <fullName>Patient Not Interested</fullName>
                </value>
                <value>
                    <fullName>Prescription Form Not Received by Doctor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rx_Follow_Up_Remarks__c</fullName>
        <label>Rx Follow Up Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_Up_Status__c</fullName>
        <label>Rx Follow Up Status:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0 - No Medication Prescribed</fullName>
                </value>
                <value>
                    <fullName>1 - Prescription for verification</fullName>
                </value>
                <value>
                    <fullName>2 -  Prescription Not Yet in Pharmacy</fullName>
                </value>
                <value>
                    <fullName>3 - Prescription Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduling_After_3_Hours__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scheduling After 3 Hours</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusChange__c</fullName>
        <label>Status Change</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>What_would_you_have_done_with_your_medic__c</fullName>
        <label>What would you have done with your medic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Emergency Room</fullName>
                </value>
                <value>
                    <fullName>Urgent Care Clinic</fullName>
                </value>
                <value>
                    <fullName>Primary Care Physician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_PrivateConsultationCtrl.cls
public class CallMD_PrivateConsultationCtrl {

    public String notes { get; set; }
    
    Private String MemberID=ApexPages.CurrentPage().getParameters().get('mid');
    
    Private String ConsultationID=ApexPages.CurrentPage().getParameters().get('cid');
    
    Public string type{get;set;}
    
    Public Member__c m;
    
    
    Public Open_Consultants__c oc;
    
    Public Open_Consultants__c OpenCons;
    
    Public CallMD_PrivateConsultationCtrl(){
    
      if(MemberID!=NULL){
        oc=[SELECT id,Consultation_Type__c,Initiated_By__c,CallBack_Number__c,Problem_History__c,
                                      CallBack_Time__c,Address__c,States__c,Scheduling_After_3_Hours__c,
                                      Pharmacy_Name_Phone__c,Meds_Prescribed_During_Consultation__c,What_would_you_have_done_with_your_medic__c,
                                      RX_Status__c,Rx_Follow_Up_Remarks__c,Pharmacy_Verifier__c, Rx_Follow_Up_Status__c,Doctorc__r.id,Doctor__c,
                                      Doctorc__r.Name,Doctorc__r.Mobile__c,Doctorc__r.State__c,
                                      CreatedDate,Member__r.FirstName__c,Member__r.LastName__c,Doctorc__c,
                                      Problem_History_cs__c,Impression_Diagnosis__c,Plan__c,Comments__c,Date__c        
                                      FROM Open_Consultants__c WHERE Member__c=:MemberID AND ID=:ConsultationID
                                      ];
       OpenCons=[SELECT id,Consultation_Type__c,Initiated_By__c,CallBack_Number__c,Problem_History__c,Consulation_Remarks__c,
                                      CallBack_Time__c,Address__c,States__c,Scheduling_After_3_Hours__c,
                                      Pharmacy_Name_Phone__c,Meds_Prescribed_During_Consultation__c,What_would_you_have_done_with_your_medic__c,
                                      RX_Status__c,Rx_Follow_Up_Remarks__c,Pharmacy_Verifier__c, Rx_Follow_Up_Status__c,Doctorc__r.id,
                                      Doctorc__r.Name,Doctorc__r.Mobile__c,Doctorc__r.State__c, Doctor_Consultation_Remark__c,
                                      CreatedDate,Member__r.FirstName__c,Member__r.LastName__c, Date_Time_of_consultation__c,
                                      Problem_History_cs__c,Impression_Diagnosis__c,Plan__c,Comments__c,Date__c, StatusChange__c       
                                      FROM Open_Consultants__c WHERE Member__c=:MemberID AND ID=:ConsultationID
                                      ];

       } 

    }

    
    Public Open_Consultants__c getOpenConsList(){
                                 
       return oc; 
  
    }
    
    
    
    Public Member__c getMember(){
    
      if(MemberID!=NULL){
       m=[SELECT id,FirstName__c,LastName__c,DateofBirth__c,Age__c,
                          Gender__c,Address_Line1__c,City__c,State__c,Home_Phone__c,
                          Work_Phone__c,Cell_Phone__c,Height__c,Weight__c 
                          FROM Member__c
                          WHERE ID=:MemberID];
     }
                          
     return m;
    
    }
    
    
     Public Open_Consultants__c getOpenCons(){
       
        //OpenCons.states__c=getMember().state__c;                             
                             
       return OpenCons;  
    
    }
  
    
    Public List<Chief_Complaint_Symptoms__c> ChiefCompSyn;
    
    Public List<Chief_Complaint_Symptoms__c> getChiefCompSynList(){
    
       ChiefCompSyn=[SELECT Name FROM Chief_Complaint_Symptoms__c];
      return ChiefCompSyn;
    
    }
  
    
    Public List<License__c> getFindDoctor(){
    
       List<License__c> docList=[SELECT Doctor__c,Doctor__r.Name,Doctor__r.Mobile__c,
                                        Doctor__r.Email__c,Doctor__r.Board_Cent__c,Doctor__r.Comments__c 
                                        FROM License__c 
                                        WHERE States__c=:getOpenCons().States__c];
      
       return docList;
    
    }
    
   
  
    
    Public void updateConsultation(){
    
      //oc.RX_Status__c=RxStatusOpt;
      
    
      update OpenCons;
    
    
    }
    
    Public void Consultation(){
    
       type='consultation';
    }
    
    Public void findDoctors(){
    
      type='findDoctors';
    }
    
    Public String DoctorId{get;set;}
    
    Public PageReference Assign(){
    
       oc.Doctorc__c=DoctorId;
       
       update oc;
       
       return null;
    
    
    }
    
    Public Void Resend(){
    }
    
    
    
}