CallMD/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>CallBack_Number__c</fullName>
        <label>CallBack Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CallBack_Time__c</fullName>
        <label>CallBack Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Consulation_Remarks__c</fullName>
        <label>Consulation Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Time_of_consultation__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date &amp; Time of consultation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meds_Prescribed_During_Consultation__c</fullName>
        <label>Meds Prescribed During Consultation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_Up_Remarks__c</fullName>
        <label>Rx Follow Up Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_up_Date_Time_Done__c</fullName>
        <label>Rx Follow-up Date &amp; Time Done</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_up_Schedule__c</fullName>
        <label>Rx Follow-up Schedule</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusChange__c</fullName>
        <label>Status Change</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_OpenConsultationsCtrl.cls
public class CallMD_OpenConsultationsCtrl {


  Public ApexPages.StandardSetController sc{get{
  
    if(sc==NULL){
  
    List<Open_Consultants__c> openConsult=[SELECT CallBack_Number__c, CallBack_Time__c, Consulation_Remarks__c,
                                                  Date__c, Date_Time_of_consultation__c, Doctor__r.Name, 
                                                  Meds_Prescribed_During_Consultation__c, Member__r.FirstName__c,
                                                  Rx_Follow_up_Date_Time_Done__c, Rx_Follow_Up_Remarks__c,
                                                  Rx_Follow_up_Schedule__c, States__c, Status__c, StatusChange__c
                                                  FROM Open_Consultants__c];
      sc=new ApexPages.StandardSetController(openConsult);
   }
      return sc;
  
  }set;}
  
  Public List<Open_Consultants__c> getOpenConsultList(){
  
     return sc.getRecords();
  }
  
    public void first(){
        sc.first();
    }
    
    public void last(){
        sc.last();
    }
    
    public void previous(){
        sc.previous();
        
    }
    public void next(){
        sc.next();
    }
    
    Public Boolean getHasNext(){
        
        return sc.getHasNext();
        
    }
    
    Public Boolean getHasPrevious(){
        
        return sc.getHasPrevious();
    }
  

  

}