CallMD/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D2C</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName__c&amp;&quot; &quot;&amp;LastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>American Independent Business Coalition</fullName>
                </value>
                <value>
                    <fullName>USHealth</fullName>
                </value>
                <value>
                    <fullName>USHealth Group</fullName>
                </value>
                <value>
                    <fullName>Benefit Services of America</fullName>
                </value>
                <value>
                    <fullName>OnCall Doctor</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Annual</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Monthly</fullName>
                </value>
                <value>
                    <fullName>Call BAA</fullName>
                </value>
                <value>
                    <fullName>CallMD Complimentary</fullName>
                </value>
                <value>
                    <fullName>CallMD One Time Consultation</fullName>
                </value>
                <value>
                    <fullName>Doctors</fullName>
                </value>
                <value>
                    <fullName>Family Care</fullName>
                </value>
                <value>
                    <fullName>Visionary</fullName>
                </value>
                <value>
                    <fullName>CallMD Sample</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>American Health Advantage True Care Discount Medical</fullName>
                </value>
                <value>
                    <fullName>American Seniors Association Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Benefit Services Of America-Test</fullName>
                </value>
                <value>
                    <fullName>CiProduct</fullName>
                </value>
                <value>
                    <fullName>Health Insurance Innovations-Extra Care Packag</fullName>
                </value>
                <value>
                    <fullName>Med Shield Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Southwest Advantage discount Plan</fullName>
                </value>
                <value>
                    <fullName>USH-PADD</fullName>
                </value>
                <value>
                    <fullName>Wellness Sheild-CallMD,Labs And Imaging</fullName>
                </value>
                <value>
                    <fullName>Wellness Shield-CallMD</fullName>
                </value>
                <value>
                    <fullName>CareExpress</fullName>
                </value>
                <value>
                    <fullName>Colonial Life</fullName>
                </value>
                <value>
                    <fullName>EnergyPlus</fullName>
                </value>
                <value>
                    <fullName>GlobalLife</fullName>
                </value>
                <value>
                    <fullName>LifeStyle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <label>Programs</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>CallBack_Number__c</fullName>
        <label>CallBack Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CallBack_Time__c</fullName>
        <label>CallBack Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Consulation_Remarks__c</fullName>
        <label>Consulation Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consultation_Type__c</fullName>
        <label>Consultation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone consultation</fullName>
                </value>
                <value>
                    <fullName>Video Consultation</fullName>
                </value>
                <value>
                    <fullName>Chat Consultation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Time_of_consultation__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date &amp; Time of consultation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meds_Prescribed_During_Consultation__c</fullName>
        <label>Meds Prescribed During Consultation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Problem_History__c</fullName>
        <label>Patient Complaint</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_Up_Remarks__c</fullName>
        <label>Rx Follow Up Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_up_Date_Time_Done__c</fullName>
        <label>Rx Follow-up Date &amp; Time Done</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_up_Schedule__c</fullName>
        <label>Rx Follow-up Schedule</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Programs__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D2C</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Providers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Providers</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipName>Provider</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programs / Packages</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs / Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Providers__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>D2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Providers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriptions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriptions</label>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Subscriptions (Child)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_SubscriptionCtrl.cls
public class CallMD_SubscriptionCtrl {

    Public String MemberID=ApexPages.CurrentPage().getParameters().get('mid');
    
    Public String SubID=ApexPages.CurrentPage().getParameters().get('id');
    
    Public String type=ApexPages.CurrentPage().getParameters().get('type');
    
    Public Member__c mem{get;set;}
    
    public Subscriptions__c sub{get;set;}
    
    public CallMD_SubscriptionCtrl(ApexPages.StandardController controller) {
    
     if(string.isNotEmpty(MemberID)){
     Mem=[SELECT id,Name,Full_Name__c FROM Member__c WHERE ID=:MemberID LIMIT 1];
     }
     
     if(string.isNotEmpty(SubID)){
       sub=(Subscriptions__c)controller.getRecord();
     }

    }
    
    Public String BenefitProvider{get;set;}
    
    Public String Program{get;set;}
    
    
    Public List<SelectOption> getBenefitProvOpt(){
    
       List<SelectOption> options =  new List<SelectOption>(); 
       
       List<Providers__c> lstProvider=[SELECT id,Name FROM Providers__c WHERE Customer_Type__c=:type];
       
       for(Providers__c p:lstProvider){
       
          options.add(new SelectOption(p.id,p.Name));
       
       }
       
       return options;
    }
    
    Public List<SelectOption> option;
    Public List<SelectOption> getProgOpt(){
    
      return option;
    }
    
    Public void ChangeBenefit(){
    
        option =  new List<SelectOption>(); 
       
        List<Programs__c> lstProgram=[SELECT id,Name FROM Programs__c 
                                                     WHERE Providers__c=:BenefitProvider AND Program_Type__c=:type];
       
        for(Programs__c p:lstProgram){
          option.add(new SelectOption(p.id,p.Name));
        }
    }
    
     Public PageReference p;
    
     Public PageReference CreateSubscription(){
     
       Subscriptions__c sub=new Subscriptions__c();
       sub.Member__c=MemberID;
       sub.Provider__c=BenefitProvider;
       sub.Program__c=Program;
       insert sub;
      if(string.isNotEmpty(sub.id)){ 
       p=new PageReference('/apex/CallMD_Member');
       p.getParameters().put('id',MemberID);
       p.getParameters().put('mode','s');
     }
       return p;
    }
    
    public pageReference UpdateSubscription(){
    
      update sub;
        PageReference p=new PageReference('/apex/CallMD_Consultations');
        p.getParameters().put('mid',MemberID);
        p.getParameters().put('mode','s');
        p.getParameters().put('sid',sub.id);
        p.getParameters().put('provId',sub.Provider__c);
        p.getParameters().put('progId',sub.Program__c);
     
        p.setRedirect(true);
      
      
      return p;
    }
    
    
    Public List<Open_Consultants__c> getOpenConsultList(){
    
     List<Open_Consultants__c> openConsult=[SELECT id,CallBack_Number__c, CallBack_Time__c, Consulation_Remarks__c,
                                                      Date__c, Date_Time_of_consultation__c, Doctor__r.Name, Problem_History__c, 
                                                      Meds_Prescribed_During_Consultation__c, Member__r.FirstName__c,Consultation_Type__c,
                                                      Member__r.LastName__c,Rx_Follow_up_Date_Time_Done__c, Rx_Follow_Up_Remarks__c,
                                                      Rx_Follow_up_Schedule__c, States__c, Status__c, StatusChange__c,CreatedBy.Name,CreatedDate
                                                      FROM Open_Consultants__c 
                                                      WHERE Member__c=:MemberID AND Subscription__c=:SubID 
                                                      
                                                  ];
    
     return openConsult;
    }

}