CallMD/src/objects/Day_of_Week__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <label>Day of Week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Day of Week</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day of Week</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Requested_Diagnostic_Procedur__c</fullName>
        <label>Additional Requested DiagnosticProcedure</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CallBack_Number__c</fullName>
        <label>CallBack Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CallBack_Time__c</fullName>
        <label>CallBack Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consultation_Status__c</fullName>
        <label>Consultation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consultation_Type__c</fullName>
        <label>Consultation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone consultation</fullName>
                </value>
                <value>
                    <fullName>Video Consultation</fullName>
                </value>
                <value>
                    <fullName>Chat Consultation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DoctorC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Open Consultation</relationshipLabel>
        <relationshipName>Open_Consultation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impression_Diagnosis__c</fullName>
        <label>Impression / Diagnosis</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <label>Initiated By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meds_Prescribed_During_Consultation__c</fullName>
        <label>Meds Prescribed During Consultation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pharmacy_Name_Phone__c</fullName>
        <label>Pharmacy Name + Phone:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pharmacy_Verifier__c</fullName>
        <label>Pharmacy Verifier:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Problem_History__c</fullName>
        <label>Patient Complaint</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Problem_History_cs__c</fullName>
        <label>Problem / History:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RX_Status__c</fullName>
        <label>RX Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prescribed Rx Medication</fullName>
                </value>
                <value>
                    <fullName>Prescribed Compound Medication</fullName>
                </value>
                <value>
                    <fullName>No Rx or Compound Medication Prescribed</fullName>
                </value>
                <value>
                    <fullName>Patient Unavailable for Consultation</fullName>
                </value>
                <value>
                    <fullName>Doctor Unavailable for Consultation</fullName>
                </value>
                <value>
                    <fullName>Patient Not Interested</fullName>
                </value>
                <value>
                    <fullName>Prescription Form Not Received by Doctor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rx_Follow_Up_Remarks__c</fullName>
        <label>Rx Follow Up Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_Up_Status__c</fullName>
        <label>Rx Follow Up Status:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0 - No Medication Prescribed</fullName>
                </value>
                <value>
                    <fullName>1 - Prescription for verification</fullName>
                </value>
                <value>
                    <fullName>2 -  Prescription Not Yet in Pharmacy</fullName>
                </value>
                <value>
                    <fullName>3 - Prescription Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduling_After_3_Hours__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scheduling After 3 Hours</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_would_you_have_done_with_your_medic__c</fullName>
        <label>What would you have done with your medic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Emergency Room</fullName>
                </value>
                <value>
                    <fullName>Urgent Care Clinic</fullName>
                </value>
                <value>
                    <fullName>Primary Care Physician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Prescribed_Medicine__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Prescribed Medicines</relationshipLabel>
        <relationshipName>Prescribed_Medicines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Prescribed Medicines</relationshipLabel>
        <relationshipName>Prescribed_Medicines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prescribed Medicine</label>
    <nameField>
        <label>Prescribed Medicine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prescribed Medicines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Scheduling__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day of Week</label>
        <referenceTo>Day_of_Week__c</referenceTo>
        <relationshipLabel>Schedullng</relationshipLabel>
        <relationshipName>Schedullng</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Schedullng</relationshipLabel>
        <relationshipName>Schedullng</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time</valueSetName>
        </valueSet>
    </fields>
    <label>Scheduling</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Schedulng ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMDDoctor_ConsultCallSummaryCtrl.cls
public class CallMDDoctor_ConsultCallSummaryCtrl {

    Private String MemberID=ApexPages.CurrentPage().getParameters().get('id');
    
    Private String ConsultationID=ApexPages.CurrentPage().getParameters().get('cid');
    
    Private String DoctorID=ApexPages.CurrentPage().getParameters().get('did');
    
    Public Member__c m;
    
    Public List<Open_Consultants__c> oc;
    
    Public List<License__c> l;
    
    Public List<Scheduling__c> schList{get;set;}
    
    Public string show{get;set;}
    
    Public Open_Consultants__c openCons{get;set;}
    
    Public List<prescribWrapper> pw{get;set;}
     
   
    Public CallMDDoctor_ConsultCallSummaryCtrl(){
    
     schList=[SELECT id,Start_Time__c,End_Time__c,Day_of_Week__r.Name FROM Scheduling__c WHERE Doctor__c=:doctorId ORDER BY Day_Of_week__r.Day_Of_week__c];
     
    try{
     openCons=[SELECT id,Member__r.FirstName__c,Member__r.Lastname__c,Consultation_Type__c,Initiated_By__c,CallBack_Number__c,Problem_History__c,
                                      CallBack_Time__c,Address__c,States__c,Scheduling_After_3_Hours__c,Date__c,DoctorC__c,Comments__c,
                                      Pharmacy_Name_Phone__c,Meds_Prescribed_During_Consultation__c,What_would_you_have_done_with_your_medic__c,
                                      RX_Status__c,Rx_Follow_Up_Remarks__c,Pharmacy_Verifier__c, Rx_Follow_Up_Status__c,Consultation_Status__c,  
                                      Problem_History_cs__c,Impression_Diagnosis__c,Plan__c,Additional_Requested_Diagnostic_Procedur__c        
                                      FROM Open_Consultants__c 
                                      WHERE DoctorC__c=:DoctorID AND Member__c=:MemberID AND ID=:ConsultationID];
     
     
     pw=new List<prescribWrapper>();
     
     if(openCons.Consultation_Status__c=='Completed'){
     
        List<Prescribed_Medicine__c> lstPredMedi=[SELECT id,Doctor__c,Open_Consultation__c,Member__c,Medicine__r.Name,Name,Instructions__c,
                                                            Strength_Form__c,Synonyms__c FROM Prescribed_Medicine__c WHERE 
                                                            Doctor__c=:DoctorID AND Open_Consultation__c=:ConsultationID AND Member__c=:MemberID];
                                                            
        for(Prescribed_Medicine__c p:lstPredMedi){
       
          prescribWrapper pm=new prescribWrapper();
          pm.prescribOption=p.Medicine__c;
          pm.Instructions=p.Instructions__c;
          pm.StrengthForm=p.Strength_Form__c;
          pm.Synonyms=p.Synonyms__c;
          pw.add(pm);
        }                                                    
     
     
     }
     else{
       for(integer i=1;i<=4;i++){
     
         pw.add(new prescribWrapper());
       }
     }
     
     }
     catch(exception e){
     }
   }

   Public List<Open_Consultants__c> getOpenConsList(){
      if(DoctorID!=null)                           
       {
        oc=[SELECT id,Member__r.FirstName__c,Member__r.Lastname__c,Consultation_Type__c,Initiated_By__c,CallBack_Number__c,Problem_History__c,
                                      CallBack_Time__c,Address__c,States__c,Scheduling_After_3_Hours__c,Date__c,DoctorC__c,Comments__c, 
                                      Pharmacy_Name_Phone__c,Meds_Prescribed_During_Consultation__c,What_would_you_have_done_with_your_medic__c,
                                      RX_Status__c,Rx_Follow_Up_Remarks__c,Pharmacy_Verifier__c, Rx_Follow_Up_Status__c,Consultation_Status__c,  
                          
                                      Problem_History_cs__c,Impression_Diagnosis__c,Plan__c,Additional_Requested_Diagnostic_Procedur__c        
                                      FROM Open_Consultants__c 
                                      WHERE DoctorC__c=:DoctorID
                                      ];
        }
       return oc; 
    
    
    }
    
    
    Public Doctor__c doc;
    
    Public Doctor__c getDoctorInfo(){
    
       if(string.isNotEmpty(DoctorID)){
       
           doc=[SELECT id,Name,Last_Name__c,Email__c,Choose_a_time_zone__c FROM Doctor__c WHERE ID=:DoctorID];
       }
       return doc;
    }

   Public Member__c getMember(){
    
      if(MemberID!=NULL){
       m=[SELECT id,FirstName__c,LastName__c,DateofBirth__c,Age__c,
                          Gender__c,Address_Line1__c,City__c,State__c,Home_Phone__c,
                          Work_Phone__c,Cell_Phone__c,Height__c,Weight__c 
                          FROM Member__c
                          WHERE ID=:MemberID];
     }
                          
     return m;
    
    }
   
   public void UpdateConsult(){
   
     
     openCons.Consultation_Status__c='Completed';
     
     List<Prescribed_Medicine__c> listPresMed=new List<Prescribed_Medicine__c>();
     
     if((!pw.isEmpty()) && openCons.Consultation_Status__c!='Completed'){
     
       for(prescribWrapper p:pw){
         
           Prescribed_Medicine__c pm=new Prescribed_Medicine__c();
           
           pm.Doctor__c=DoctorID;
           pm.Open_Consultation__c=ConsultationID;
           pm.Member__c=MemberID;
           pm.Medicine__c=p.prescribOption;
           pm.Instructions__c=p.Instructions;
           pm.Strength_Form__c=p.StrengthForm;
           pm.Synonyms__c=p.Synonyms;
          
           
           listPresMed.add(pm);
       
       }
       
       if(!listPresMed.isEmpty()){
         insert listPresMed;
       }
     
     }
     
   
     update openCons;
    
   }
   
   
   Public List<License__c> getLicenseList(){
   
    if(DoctorID!=NULL){
       l=[SELECT id,Name,States__c,Expiration_date__c 
                                 FROM License__c
                                 WHERE Doctor__c=:DoctorID];
    }
      return l;                            
   }
    
  Public Member__c mem;
    
  Public Member__c getMemberDetails(){
    
     if(MemberID!=null){
      mem=[SELECT id,FirstName__c,LastName__c,DateofBirth__c,Age__c,
                          Gender__c,Address_Line1__c,City__c,State__c,Home_Phone__c,
                          Work_Phone__c,Cell_Phone__c,Height__c,Weight__c 
                          FROM Member__c
                          WHERE ID=:MemberID];
      }
      return mem;
    }
    
    
  
    
    Public Class prescribWrapper{
       
       public string prescribOption{get;set;}
       Public List<selectOption> pOpt{get;set;}
       Public string Instructions{get;set;}
       Public string StrengthForm{get;set;}
       Public string Synonyms{get;set;}
       
       
       Public prescribWrapper(){
         List<Medicines__c> med=[SELECT id,Name FROM Medicines__c LIMIT 999];
          pOpt=new List<selectOption>();
           for(Medicines__c m:med){
            pOpt.add(new SelectOption(m.id,m.name));
            }
        }
    }
    
    
   Public List<Scheduling__c> getSchedulingList(){
    
      return schList;
    }
    
    Public void UpdateSchedule(){
      update Doc;
      update schList;
    } 
    
    public void showDashboard(){
    
       show='Dashboard';
    } 
    
    public void showschedulling(){
      show='Schedulling';
    }
    
    Public void showLicenses(){
      show='License';
    }
    
    Public pageReference EPrescription(){
      return page.CallMD_EPrescription;
    }
    
}