CallMD/src/objects/Day_of_Week__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <label>Day of Week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Day of Week</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day of Week</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Scheduling__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day of Week</label>
        <referenceTo>Day_of_Week__c</referenceTo>
        <relationshipLabel>Schedullng</relationshipLabel>
        <relationshipName>Schedullng</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Schedullng</relationshipLabel>
        <relationshipName>Schedullng</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time</valueSetName>
        </valueSet>
    </fields>
    <label>Scheduling</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Schedulng ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_SchedulingController.cls
public class CallMD_SchedulingController {
   
  public DateTime currentTime{get;set;}
  
  Public string currTime{get;set;}
  
  private string Day;
  
  public CallMD_SchedulingController(){
     Date d = date.today();
     Datetime myDate = datetime.newInstance(d.year(), d.month(), d.day());
     currentTime = DateTime.Now();
     currTime= myDate.format('h:mm a');
     day = myDate.format('EEEE');
  }


  public List<Scheduling__c> getSchedulingList(){
  
     List<Scheduling__c> schList= [SELECT Doctor__r.Name, Day_of_Week__r.Day_of_Week__c, Start_Time__c, 
                                          End_Time__c,Doctor__r.State__c,Day_of_Week__r.Name 
                                          FROM Scheduling__c 
                                          WHERE Doctor__r.State__c='NY'
                                          AND Day_of_Week__r.Name=:day AND Start_Time__c=:currTime
                                          ORDER BY Day_of_Week__r.Day_of_Week__c ASC];

      system.debug('Sch List:: '+schList);
      
     return schList;
  
  }
  
   public List<Scheduling__c> getUnAvailbleSchedulingList(){
  
     List<Scheduling__c> schList= [SELECT Doctor__r.Name, Day_of_Week__r.Day_of_Week__c, Start_Time__c, 
                                          End_Time__c,Doctor__r.State__c,Day_of_Week__r.Name 
                                          FROM Scheduling__c 
                                          WHERE Doctor__r.State__c='NY'
                                          AND Day_of_Week__r.Name=:day
                                          ORDER BY Day_of_Week__r.Day_of_Week__c ASC];

      system.debug('Sch List:: '+schList);
      
     return schList;
  
  }


}