CallMD/src/objects/Day_of_Week__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <label>Day of Week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Day of Week</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day of Week</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>inActive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expiration_date__c</fullName>
        <label>Expiration date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Scheduling__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day of Week</label>
        <referenceTo>Day_of_Week__c</referenceTo>
        <relationshipLabel>Schedullng</relationshipLabel>
        <relationshipName>Schedullng</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Schedullng</relationshipLabel>
        <relationshipName>Schedullng</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time</valueSetName>
        </valueSet>
    </fields>
    <label>Scheduling</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Schedulng ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_DoctorExtCtrl.cls
public class CallMD_DoctorExtCtrl {

   Public Doctor__c doc;
   Private List<License__c> licenses;
   Private String doctorId=ApexPages.CurrentPage().getParameters().get('id');
   
   public string filename{get;set;}
   public transient blob filebody{get;set;}
   
   public String mode{get{
   
     return ApexPages.CurrentPage().getParameters().get('mode');
   }set;}
   
   Public Boolean isShow{get;set;}
   
   Public List<Scheduling__c> schList{get;set;}
   
   public CallMD_DoctorExtCtrl(ApexPages.StandardController controller) {
    
      doc=(Doctor__c)controller.getRecord();
      
      schList=[SELECT id,Start_Time__c,End_Time__c,Day_of_Week__r.Name FROM Scheduling__c WHERE Doctor__c=:doctorId ORDER BY Day_Of_week__r.Day_Of_week__c];

    }
    
    Public pageReference save(){
     pageReference p;
     try{
      insert doc;
      p=new pageReference('/apex/CallMD_Doctor');
      p.getParameters().put('id',doc.id);
      p.getParameters().put('mode','e');
      p.setRedirect(true);
      }
      catch(exception e){}
      
      return p;
    }
    
    Public pageReference updateDoctor(){
     try{
      update doc;
      p=new pageReference('/apex/CallMD_Doctor');
      p.getParameters().put('id',doctorID);
      p.getParameters().put('mode','s');
      p.setRedirect(true);
     }
     catch(exception e){}
     
     return p;
    }
    
    Public pageReference updateDoctor2(){
     try{
      update doc;
      p=new pageReference('/apex/CallMD_HomePage');
      p.getParameters().put('did',doctorID);
      p.setRedirect(true);
     }
     catch(exception e){}
     
     return p;
    }
    
 
    Public List<License__c> getDoctorLicenseList(){
     
     if(doctorId!=null){
       licenses=[SELECT Name,States__c,Status__c,Expiration_date__c FROM License__c WHERE Doctor__c=:doctorId];
     }  
       return licenses;
       
    }
    
    Public List<Scheduling__c> getSchedulingList(){
    
      return schList;
    }
    
    Public void UpdateSchedule(){
      update schList;
    }
    
    Public pageReference p;
    
    Public PageReference CreateLicense(){
    
      p=new pageReference('/apex/CallMD_DoctorLicenses');
      p.getParameters().put('did',doc.id);
      p.getParameters().put('name',doc.Name);
      p.setRedirect(true);
      return p;
    }
    
    Public pageReference edit(){
    
       p=new PageReference('/apex/CallMD_Doctor');
       p.getParameters().put('id',doctorId);
       p.getParameters().put('mode','e');
       p.getParameters().put('retPageName','CallMD_Doctor');
       p.setRedirect(true);
       return p; 
    }
    
     public void upload(){
    
      Attachment att = new Attachment();
      att.Name=filename;
      att.body=filebody;
      att.parentId=doctorId;
      insert att;
    
    }
    
    public List<Attachment> getDocList(){
    
    
      List<Attachment> attachList;
    
      if(string.isNotEmpty(DoctorId)){
      
         attachList = [SELECT id,Name FROM Attachment WHERE ParentId =: DoctorId];
      }
      
      return attachList;
    
    
    }
    
    
    Public PageReference Cancel(){
    
       p=new PageReference('/apex/CallMD_Doctor');
       p.getParameters().put('id',doctorId);
       p.getParameters().put('mode','s');
       p.getParameters().put('retPageName','CallMD_Doctor');
       p.setRedirect(true);
       return p; 
    
    }
    
    Public PageReference CancelDoctor(){
    
       p=new PageReference('/apex/CallMD_HomePage');
       p.getParameters().put('did',doctorId);
       p.setRedirect(true);
       return p; 
    
    }

}