CallMD/src/objects/Day_of_Week__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <label>Day of Week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Day of Week</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day of Week</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Choose_a_time_zone__c</fullName>
        <label>Choose a time zone:</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern US</fullName>
                </value>
                <value>
                    <fullName>Central US</fullName>
                </value>
                <value>
                    <fullName>Mountain US</fullName>
                </value>
                <value>
                    <fullName>Arizona US</fullName>
                </value>
                <value>
                    <fullName>Pacific  US</fullName>
                </value>
                <value>
                    <fullName>Alaska US</fullName>
                </value>
                <value>
                    <fullName>Hawaii US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Scheduling__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day of Week</label>
        <referenceTo>Day_of_Week__c</referenceTo>
        <relationshipLabel>Schedullng</relationshipLabel>
        <relationshipName>Schedullng</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Schedullng</relationshipLabel>
        <relationshipName>Schedullng</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time</valueSetName>
        </valueSet>
    </fields>
    <label>Scheduling</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Schedulng ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRDoctorByTime.cls
@RestResource(urlMapping='/v1/DoctorByTime/*')
global class CallMD_IVRDoctorByTime {

    @HttpGet
    global static List<DoctorWrapper> doGetDoctorByTime(){
    
      RestRequest req=RestContext.request;
      
      string state=req.params.get('state');
        
        List<Doctor__c> docList=[SELECT id,Name,Last_Name__c,Email__c,Mobile__c,State__c,Choose_a_time_zone__c
                                       FROM Doctor__c 
                                       WHERE State__c=:state];
        
        List<DoctorWrapper> lstDoctorWrap =new List<DoctorWrapper>();
         
        Set<Id> doctorIds=new Set<Id>(); 
        
        for(Doctor__c d:docList){
            doctorIds.add(d.id);
        }
        
        List<Scheduling__c > schList=[SELECT id,Day_Of_Week__r.Day_Of_week__c,Day_Of_Week__r.Name,Doctor__c,
                                             Start_Time__c,End_Time__c FROM Scheduling__c 
                                             WHERE Doctor__c IN:doctorIds];
        
        map<id,List<Scheduling__c>> mapScheduling=new map<id,List<Scheduling__c>>();
        
        for(Scheduling__c sch:schList){
            
            if(!mapScheduling.containsKey(sch.Doctor__c)){
                mapScheduling.put(sch.Doctor__c,new List<Scheduling__c>{sch});
            }
            else{
                mapScheduling.get(sch.Doctor__c).add(sch); 
            }
        }
        
        for(Doctor__c doc:docList){
          if(mapScheduling.get(doc.id)!=null)  {   
          DoctorWrapper doctorWrap=new DoctorWrapper();
          List<DoctorTimings> lstDocTime=new List<DoctorTimings>();
          doctorWrap.doctorId=doc.id;
          doctorWrap.doctorTimeZone=doc.Choose_a_time_zone__c; 
          doctorWrap.firstname=doc.Name;
          doctorWrap.lastname=doc.Last_Name__c;
          doctorWrap.email=doc.Email__c;
          doctorWrap.phone=doc.Mobile__c;
          doctorWrap.state=doc.State__c;
             
                for(Scheduling__c sch:mapScheduling.get(doc.id)){
                    
                    DoctorTimings docTime=new DoctorTimings();
                    docTime.day=sch.Day_Of_Week__r.Day_Of_week__c;
                    docTime.startTime=sch.Start_Time__c;
                    docTime.endTime=sch.End_Time__c;
                    lstDocTime.add(docTime);
                    
                }
          doctorWrap.DoctorTimings=lstDocTime;
          lstDoctorWrap.add(doctorWrap);
          }
        }
        return lstDoctorWrap;
        
    }

    global class DoctorWrapper{
        public string doctorId;
        public string doctorTimeZone;
        public string firstname;
        public string lastname;
        public string email;
        public string phone;
        public string state; 
        Public List<DoctorTimings> DoctorTimings;
        
        /* public DoctorWrapper(string fname,string lname,string email,string phone,string state,List<DoctorTimings> DoctorTimings){
            firstname=fname;
            lastname=lname;
            email=email;
            phone=phone;
            state=state;
            DoctorTimings=DoctorTimings;
        } */
        
    }
    
    Public class DoctorTimings{
         public string day;
         public string startTime;
         public string endTime;
    }
    

}