CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Confirm_Password__c</fullName>
        <label>Confirm Password</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>25</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Reset_Password_Date__c</fullName>
        <label>Reset Password Date</label>
        <type>Date</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_DoctorResetPasswordCtrl.cls
public class CallMD_DoctorResetPasswordCtrl {

   Public string pwd{get;set;}
    Public String confirmpwd{get;set;}
    Public Doctor__c doc{get;set;}
    Private string doctorId=ApexPages.CurrentPage().getParameters().get('id');
    
    Public CallMD_DoctorResetPasswordCtrl(){
    if(doctorId!=null){
      doc=[SELECT id,Confirm_Password__c,Password__c 
                  FROM Doctor__c WHERE id=:doctorId];
    }
    }
    
    
    Public PageReference p;
    
    public PageReference ChangePassword() {
    
       if(pwd!=confirmpwd){
       
       }
       else{
         doc.Password__c=pwd;
         doc.Confirm_Password__c=confirmpwd;
         doc.Password__c=pwd;
         doc.Reset_Password_Date__c=Date.Today();
         update doc;
         p=new PageReference('/apex/CallMD_Thankyou');
       p.setRedirect(true);
       }
    
       
       return p;
    }

}