CallMD/src/objects/Doctor__c.object
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_DoctorLicensesExtCtrl.cls
public class CallMD_DoctorLicensesExtCtrl {

   Public License__c license{get;set;}
   Private String doctorId=ApexPages.CurrentPage().getParameters().get('did');
   public pageReference p;
   
   Public String doctorName{get
   {
     return ApexPages.CurrentPage().getParameters().get('Name');
   }set;}

    public CallMD_DoctorLicensesExtCtrl(ApexPages.StandardController controller) {
       license=(License__c)controller.getRecord();
    }
    
    Public PageReference Save(){
    
      license.Doctor__c=doctorId;
    
      insert license;
      if(license.id!=null){
      p=new pageReference('/apex/CallMD_Doctor');
      p.getParameters().put('id',doctorId);
      p.getParameters().put('mode','e');
      p.setRedirect(true);
      }
      return p;
    }
    
    Public pageReference updateLicenses(){
    
      update license;
      
      p=new pageReference('/apex/CallMD_Doctor');
      p.getParameters().put('id',doctorId);
      p.getParameters().put('mode','e');
      p.setRedirect(true);
      return p;
    }

}