CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>InActive_Licenses__c</fullName>
        <label>InActive Licenses</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_States__c</fullName>
        <label>License States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>inActive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/DoctorLicenseTriggerHandler.cls
public class DoctorLicenseTriggerHandler {
    
    Public static void DoctorLicense(List<License__c> lstLicen){
        
        Set<Id> doctorIds=new Set<Id>();
        String activeStatesLicen='';
        String inActiveStatesLicen='';
        
        Map<id,Doctor__c> docList=new Map<id,Doctor__c>();
        
        for(License__c l:lstLicen){
            doctorIds.add(l.Doctor__c);  
        }
        if(!doctorIds.isEmpty()) {
        Map<id,Doctor__c> mapDoctor=new Map<id,Doctor__c>([SELECT id,License_States__c,InActive_Licenses__c 
                                                                            FROM Doctor__c 
                                                                            WHERE ID IN:doctorIds]);
        
        for(License__c l:[SELECT id,States__c,Status__c FROM License__c WHERE Doctor__c IN:doctorIds AND status__c='Active']){
           
                activeStatesLicen+=l.States__c+';';
        }
        
        for(License__c l:[SELECT id,States__c,Status__c FROM License__c WHERE Doctor__c IN:doctorIds AND status__c='InActive'])
        {
             inActiveStatesLicen+=l.States__c+';';                
        }
        
        for(License__c l:lstLicen){  
            Doctor__c d=MapDoctor.get(l.Doctor__c);
            if(activeStatesLicen!=null || activeStatesLicen!=''){
                d.License_States__c=activeStatesLicen.removeEnd(';');
            }
            if(inActiveStatesLicen!=null || inActiveStatesLicen!=''){
                d.InActive_Licenses__c=inActiveStatesLicen.removeEnd(';');
            } 
            docList.put(d.id,d);
        }
        if(!docList.isEmpty()){
            update docList.values();
        }
    }
   }
}