CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRDRStateByTime.cls
@RestResource(urlMapping='/v1/doctorstatetime')
global class CallMD_IVRDRStateByTime {
    
    
    @HttPGet
    global static responseStatesTime doGetStates(){
        
        RestRequest req=RestContext.request;
        RestResponse res=RestContext.response;
        
        responseStatesTime statesTime=new responseStatesTime();
        
        try{
            List<Doctor__c> docList=[SELECT Name,State__c FROM Doctor__c 
                                     WHERE State__c=:req.params.get('state')];
            if(!docList.isEmpty()){
                statesTime.doctor=docList;
                statesTime.status='200';
                statesTime.statusmsg='success';
            }
            else{ 
                statesTime.doctor=null;
                statesTime.status='200';
                statesTime.statusmsg='No Doctor Found'; 
            }
        }
        catch(exception e){} 
        
        return statesTime;
        
    }
    
    global class responseStatesTime{
        Public List<Doctor__c> doctor;
        public string status;
        Public string statusmsg;
    }
    
    
}