CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>InActive_Licenses__c</fullName>
        <label>InActive Licenses</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_States__c</fullName>
        <label>License States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CallMD</fullName>
                </value>
                <value>
                    <fullName>PetMD</fullName>
                </value>
                <value>
                    <fullName>DentalMD</fullName>
                </value>
                <value>
                    <fullName>EducationMD</fullName>
                </value>
                <value>
                    <fullName>CorrectionsMD</fullName>
                </value>
                <value>
                    <fullName>TravelMD</fullName>
                </value>
                <value>
                    <fullName>FitMD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>inActive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>User name</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_PaginationCtrl.cls
public class CallMD_PaginationCtrl {

        Public String firstname{get;set;}
        Public String lastname{get;set;}
        Public String phone{get;set;}
        Public string status{get;set;}
        Public string licenseState{get;set;}
        public List<Doctor__c> doctorsList {get;set;}
       
        List<string> conditions = new List<string>();
        private integer totalRecs = 0;
        private integer OffsetSize = 0;
        private integer LimitSize= 10;

        Public PageReference p;
        Public PageReference NavigateToDoctor(){
        
            p=new PageReference('/apex/CallMD_Doctor');
            p.setRedirect(true);
            return p;
        }
        
       public void searchSobject(){
            totalRecs = 0;
            OffsetSize = 0;
            /* if(doctorsList !=null && doctorsList.size()>0){
                doctorsList=null;
            } */
            searchSobjects();
            conditions.clear();
        }
        
        public Void searchSobjects(){

            if(doctorsList != null && !doctorsList.isEmpty()){
                doctorsList.clear();
            }
            String strQuery ='SELECT Id,Name,Last_Name__c,Status__c,InActive_Licenses__c,Username__c,Email__c,Primary_Phone__c,Secondary_Phone__c,Date_Of_Birth__c,License_States__c,Product_Type__c FROM Doctor__c';
           
            if(firstname !=null && firstname!=''){
                conditions.add('Name Like \'%' +firstname +'%\' ');
            }
            
            if(lastname !=null && lastname!=''){
                conditions.add('Last_Name__c Like \'%' +lastname +'%\' ');
            }
            
            if(phone !=null &&  phone!=''){
                conditions.add('Secondary_Phone__c Like \'%'+phone+'%\' ');
            }
            
            if(status!=null && status!=''){
                conditions.add('Status__c Like \'%'+status+'%\' ');
            }
            
            /* if(LicenseState !=null && LicenseState !=''){
                conditions.add('License_States__c  includes \'%' +licenseState+'%\' ');
            } */
            
            
            if (conditions.size() > 0) {
                strQuery += '  WHERE ' + conditions[0];
                for (Integer i = 1; i < conditions.size(); i++)
                    strQuery += '  AND ' + conditions[i];
            }
            if(totalRecs !=null && totalRecs ==0){
                List<Doctor__c> accTemp = Database.query(strQuery);
                totalRecs = (accTemp !=null &&accTemp.size()>0)?accTemp.size():0;
            }
        
            strQuery += ' ORDER BY Name  ASC, CreatedDate DESC LIMIT :LimitSize OFFSET :OffsetSize';
            doctorsList  =Database.query(strQuery);
        }
        
        public void first()
        {
            OffsetSize = 0;
            searchSobjects();
        }
        public void previous()
        {
            OffsetSize = (OffsetSize-LimitSize);
            searchSobjects();
        }
        public void next()
        {
            OffsetSize = OffsetSize + LimitSize;
            searchSobjects();
        }
        public void last()
        {
            OffsetSize = totalrecs - math.mod(totalRecs,LimitSize);
            searchSobjects();
        }
        public boolean getHasPrevious()
        {
            Boolean res1;
            if(OffsetSize == 0){
                
                res1=true;
            }
            
            return res1;
        }
        public boolean getHasNext()
        {
            Boolean res1;
            if((OffsetSize + LimitSize) > totalRecs){
                
                res1=true;
            }
            
            return res1;
       
        }
   }