CallMD/src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>Last_Name__c&amp;&quot; &quot;&amp;Name&amp;&quot; &quot;&amp;Middle_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>inActive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName__c&amp;&quot; &quot;&amp;LastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Provider__c</fullName>
        <formula>Subscription__r.Provider_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Benefit Provider</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallBack_Number__c</fullName>
        <label>CallBack Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CallBack_Time__c</fullName>
        <label>CallBack Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Consulation_Remarks__c</fullName>
        <label>Consulation Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consultation_Type__c</fullName>
        <label>Consultation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone consultation</fullName>
                </value>
                <value>
                    <fullName>Video Consultation</fullName>
                </value>
                <value>
                    <fullName>Chat Consultation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Time_of_consultation__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date &amp; Time of consultation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DoctorC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Open Consultation</relationshipLabel>
        <relationshipName>Open_Consultation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor_Consultation_Remark__c</fullName>
        <label>Doctor Consultation Remark</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Meds_Prescribed_During_Consultation__c</fullName>
        <label>Meds Prescribed During Consultation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_Up_Remarks__c</fullName>
        <label>Rx Follow Up Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_up_Date_Time_Done__c</fullName>
        <label>Rx Follow-up Date &amp; Time Done</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rx_Follow_up_Schedule__c</fullName>
        <label>Rx Follow-up Schedule</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusChange__c</fullName>
        <label>Status Change</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Subscriptions__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Open Consultation</relationshipLabel>
        <relationshipName>Subscription</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <formula>Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(B2B_D2C_Ref__c ==&apos;D2C&apos;,IF(AND(ISPICKVAL(Subscription_Type__c,&quot;New&quot;),ISPICKVAL(Payment__c ,&quot;Successful&quot;),End_Date__c&gt;=TODAY(),Remaining_Consultation__c&gt;=1),&apos;Active&apos;,
IF(AND(ISPICKVAL(Subscription_Type__c,&quot;Renewal&quot;),End_Date__c&gt;=TODAY(),Consultation_Renewal__c &gt;=1),&apos;Active&apos;,&apos;Expired&apos;)),IF(AND(B2B_D2C_Ref__c ==&apos;B2B&apos;,End_Date__c&gt;=TODAY()),&apos;Active&apos;,&apos;Expired&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_OpenConsultations.cls
public class CallMD_OpenConsultations {

    public CallMD_OpenConsultations(ApexPages.StandardController controller) {

    }
    
   
    Public ApexPages.StandardSetController sc{get{
  
    if(sc==NULL){
  
    List<Open_Consultants__c> openConsult=[SELECT CallBack_Number__c, CallBack_Time__c, Consulation_Remarks__c,
                                                  Date__c, Date_Time_of_consultation__c, Doctorc__r.Name, Consultation_Type__c, 
                                                  Meds_Prescribed_During_Consultation__c, Member__r.FirstName__c,Member__r.Full_Name__c,
                                                  Rx_Follow_up_Date_Time_Done__c, Rx_Follow_Up_Remarks__c,Doctor_Consultation_Remark__c,
                                                  Rx_Follow_up_Schedule__c, States__c, Status__c, StatusChange__c,Subscription__r.Program_Name__c,
                                                  Benefit_Provider__c,CreatedBy.Name,CreatedDate
                                                  FROM Open_Consultants__c ORDER BY CreatedDate DESC];
      sc=new ApexPages.StandardSetController(openConsult);
   }
   
      sc.setPageSize(100);
      return sc;
  
  }set;}
  
  Public List<Open_Consultants__c> getOpenConsultList(){
  
     return sc.getRecords();
  }
  
  Public void first(){
    sc.first();
  }
  
  Public void last(){
    sc.last();
  }
  
  Public void previous(){
    sc.previous();
  }
  
  Public void next(){
    sc.next();
  }
  
  Public Boolean getHasNext(){
   return sc.gethasNext();
  }
  
  Public Boolean getHasPrevious(){
  
   return sc.getHasPrevious();
  }

}