CallMD/src/objects/Immunization_Members__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Immunization Members</relationshipLabel>
        <relationshipName>Immunization_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Immunization Members</label>
    <nameField>
        <label>Immunization Members	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immunization Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_ImmunizationMemExt.cls
public class CallMD_ImmunizationMemExt {
    Private String MemberID=ApexPages.CurrentPage().getParameters().get('mid');
    Public Immunization_Members__c immuzMem{get;set;}
    public CallMD_ImmunizationMemExt(ApexPages.StandardController controller) {
      immuzMem=(Immunization_Members__c)controller.getRecord();
    }
    
    Public PageReference p;
    Public PageReference Save(){
      immuzMem.Member__c=MemberID;
      insert immuzMem;
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
      
    }
    
    Public PageReference Cancel(){
    
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
      
    }

}