CallMD/src/objects/Medications__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Medications</relationshipLabel>
        <relationshipName>Medications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medications</label>
    <nameField>
        <label>Medications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_MedicationsExt.cls
public class CallMD_MedicationsExt {

    Private String MemberID=ApexPages.CurrentPage().getParameters().get('mid');
    Public Medications__c medi{get;set;}
    public CallMD_MedicationsExt(ApexPages.StandardController controller) {
       medi=(Medications__c)controller.getRecord();
    }
    
    Public PageReference p;
    Public PageReference Save(){
      medi.Member__c=MemberID;
      insert medi;
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
    }
    
    Public PageReference Cancel(){
    
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
    }

}