CallMD/src/objects/MedicalTypes__c.object
<CustomObject>
    <label>MedicalTypes</label>
    <nameField>
        <displayFormat>MTID-{0000}</displayFormat>
        <label>MedicalTypeID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MedicalTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Symptoms__c.object
<CustomObject>
    <fields>
        <fullName>MedicalTypes__c</fullName>
        <label>MedicalTypes</label>
        <referenceTo>MedicalTypes__c</referenceTo>
        <relationshipLabel>Symptoms</relationshipLabel>
        <relationshipName>Symptoms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Symptoms</label>
    <nameField>
        <displayFormat>SYM-{0000}</displayFormat>
        <label>SymptonsID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Symptoms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_SymptomsExtCtrl.cls
public class CallMD_SymptomsExtCtrl {

  Public Symptoms__c sym{get;set;}
  
  Public PageReference p;
  
  Private String medicalTypeID=ApexPages.CurrentPage().getParameters().get('MediTypeId');

    public CallMD_SymptomsExtCtrl(ApexPages.StandardController controller) {
    
       sym=(Symptoms__c)controller.getRecord();
     
      
    }
    
    Public PageReference createSymptoms(){
    
     try{
      
       sym.MedicalTypes__c=medicalTypeID;
       insert sym;
       p=new PageReference('/apex/CallMD_MedicalConditions');
        p.getParameters().put('tab','Admin');
       p.getParameters().put('id',MedicalTypeID);
       p.setRedirect(true);
     }
     catch(exception e){
     }  
            
     return p;
    }
    
    Public PageReference UpdateSymptoms(){
    
    try{
      update sym;
      
      p=new PageReference('/apex/CallMD_MedicalConditions');
       p.getParameters().put('tab','Admin');
      p.getParameters().put('id',MedicalTypeID);
      p.setRedirect(true);
     }
     catch(exception e){
     
     }
     return p;
    }

}