CallMD/src/objects/Medical_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Medical Conditions</relationshipLabel>
        <relationshipName>Medical_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medical Conditions</label>
    <nameField>
        <label>Medical Conditions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_MedicalMemCondExt.cls
public class CallMD_MedicalMemCondExt {

    Private String MemberID=ApexPages.CurrentPage().getParameters().get('mid');
    Public Medical_Conditions__c mediCon{get;set;}
    
    public CallMD_MedicalMemCondExt(ApexPages.StandardController controller) {
      mediCon=(Medical_Conditions__c)controller.getRecord();
    }
    
    Public PageReference p;
    Public PageReference Save(){
      mediCon.Member__c=MemberID;
      insert mediCon;
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
    }
    
    Public PageReference Cancel(){
    
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
    }

}