CallMD/src/objects/MedicalTypes__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <externalId>true</externalId>
        <label>Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>MedicalTypes</label>
    <nameField>
        <displayFormat>MTID-{0000}</displayFormat>
        <label>MedicalTypeID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MedicalTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Symptoms__c.object
<CustomObject>
    <fields>
        <fullName>MedicalTypes__c</fullName>
        <label>MedicalTypes</label>
        <referenceTo>MedicalTypes__c</referenceTo>
        <relationshipLabel>Symptoms</relationshipLabel>
        <relationshipName>Symptoms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SymptomName__c</fullName>
        <label>SymptomName</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Symptoms</label>
    <nameField>
        <displayFormat>SYM-{0000}</displayFormat>
        <label>SymptonsID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Symptoms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_AdminCtrlTest.cls
@isTest
Private class CallMD_AdminCtrlTest {
    testMethod static void AdminCtrl(){
        
        List<MedicalTypes__c> medicalTypesList=new List<MedicalTypes__c>();
        
        MedicalTypes__c mt1=new MedicalTypes__c(Name__c='BLOOD / CANCER');
        medicalTypesList.add(mt1);
        MedicalTypes__c mt2=new MedicalTypes__c(Name__c='ENT (EAR/NOSE/THROAT)');
        medicalTypesList.add(mt2);
        MedicalTypes__c mt3=new MedicalTypes__c(Name__c='BONES / JOINTS / MUSCLES (RHEUMATOLOGY)');
        medicalTypesList.add(mt3);
        MedicalTypes__c mt4=new MedicalTypes__c(Name__c='SKIN');
        medicalTypesList.add(mt4);      
        insert medicalTypesList;
        
        List<Symptoms__c> symList=new List<Symptoms__c>();
        
        Symptoms__c sym1=new Symptoms__c(SymptomName__c ='Testing1',MedicalTypes__c=medicalTypesList[0].id);
        Symptoms__c sym2=new Symptoms__c(SymptomName__c ='Testing2',MedicalTypes__c=medicalTypesList[0].id);
        
        symList.add(sym1);
        symList.add(sym2);
        insert symList;
       
        
        ApexPages.CurrentPage().getParameters().put('MedTypeID',medicalTypesList[0].id);
        
        CallMD_AdminCtrl adminCtrl=new CallMD_AdminCtrl();
        adminCtrl.mt.Name__c='BLOOD / CANCER';
        adminCtrl.getNewMediTypes();
        adminCtrl.createMedicalTypes();
        adminCtrl.showMedicalTypes.Name__c='BLOOD / CANCER';
        
        
       
    }

}