CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Physicians__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Physicians</relationshipLabel>
        <relationshipName>Physicians</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Physicians</label>
    <nameField>
        <label>Physicians Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_Physicians.cls
public class CallMD_Physicians {
    
    Public Physicians__c phy{get;set;}
    Private String MemberID=ApexPages.CurrentPage().getParameters().get('mid');
    public CallMD_Physicians(ApexPages.StandardController controller) {
      phy=(Physicians__c)Controller.getRecord();
    }
    
    Public PageReference p;
    Public PageReference Save(){
      phy.Member__c=MemberID;
      insert phy;
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
      
    }
    
    Public PageReference Cancel(){
    
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
      
    }

}