CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Surgeries__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Surgeries</relationshipLabel>
        <relationshipName>Surgeries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Surgeries</label>
    <nameField>
        <label>Surgeries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgeries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_SurgeriesExt.cls
public class CallMD_SurgeriesExt {

    public Surgeries__c s{get;set;}
    Private String MemberID=ApexPages.CurrentPage().getParameters().get('mid');
    public CallMD_SurgeriesExt(ApexPages.StandardController controller) {
       s=(Surgeries__c)Controller.getRecord();
    }
    
    Public PageReference p;
    Public PageReference Save(){
      s.Member__c=MemberID;
      insert s;
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
      
    }
    
    Public PageReference Cancel(){
    
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
      
    }
    
    

}