CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>CallMDUserName__c</fullName>
        <label>CallMDUserName</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRVerifyPhone.cls
@RestResource(urlMapping='/v1/verifyphone/*')
global class CallMD_IVRVerifyPhone {
    
    @HttpGet
    global static responsePhone doVerifyPhone(){
        
        RestRequest req=RestContext.request;
        RestResponse res=RestContext.response;
        responsePhone resPhone=new responsePhone();
        
        string Phone=req.params.get('PhoneNumber');
        List<Member__c> memDetails;
        try{
            memDetails=[SELECT id,Cell_Phone__c,CallMDUserName__c  FROM Member__c WHERE Cell_Phone__c Like:Phone];
            
            if(memDetails.size()==1){
                resPhone.status='success';
                resPhone.phonenumber=memDetails[0].Cell_Phone__c;
                resPhone.callMDAccountNumber=memDetails[0].CallMDUserName__c;
                resPhone.statusmsg='Found';
                resPhone.id=memDetails[0].id;
            }
            else{
                resPhone.status='Failure'; 
                resPhone.statusmsg='Not Found';
            }
        }
        catch(Exception e){
            
            
        }
        return resPhone;
    }
    

    global class responsePhone{
        public string status;
        public string phonenumber;
        public string callMDAccountNumber;
        public string statusmsg;
        public string id;
    }
}