CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>CallBack_Number__c</fullName>
        <label>CallBack Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Incoming_Number__c</fullName>
        <label>Incoming Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>True</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_transaction_id__c</fullName>
        <label>Payment transaction id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Problem_History__c</fullName>
        <label>Patient Complaint</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PetMD</fullName>
                </value>
                <value>
                    <fullName>CallMD</fullName>
                </value>
                <value>
                    <fullName>EducationMD</fullName>
                </value>
                <value>
                    <fullName>TravelMD</fullName>
                </value>
                <value>
                    <fullName>FitMD</fullName>
                </value>
                <value>
                    <fullName>DentalMD</fullName>
                </value>
                <value>
                    <fullName>CorrectionsMD</fullName>
                </value>
                <value>
                    <fullName>HopeMD</fullName>
                </value>
                <value>
                    <fullName>DiagonosticsMD</fullName>
                </value>
                <value>
                    <fullName>PSYMD</fullName>
                </value>
                <value>
                    <fullName>SOSMD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recording_ID__c</fullName>
        <label>Recording ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Subscriptions__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Open Consultation</relationshipLabel>
        <relationshipName>Subscription</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(B2B_D2C_Ref__c ==&apos;D2C&apos;,IF(AND(ISPICKVAL(Subscription_Type__c,&quot;New&quot;),ISPICKVAL(Payment__c ,&quot;Successful&quot;),End_Date__c&gt;=TODAY(),Remaining_Consultation__c&gt;=1),&apos;Active&apos;,
IF(AND(ISPICKVAL(Subscription_Type__c,&quot;Renewal&quot;),End_Date__c&gt;=TODAY(),Consultation_Renewal__c &gt;=1),&apos;Active&apos;,&apos;Expired&apos;)),IF(AND(B2B_D2C_Ref__c ==&apos;B2B&apos;,End_Date__c&gt;=TODAY()),&apos;Active&apos;,&apos;Expired&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriptions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriptions</label>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Subscriptions (Child)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRInitiateConsultation.cls
@RestResource(urlMapping='/v1/CallMD_IVRInitiateConsultation/*')
global class CallMD_IVRInitiateConsultation {
    
    @HttPPost
    global static ConsultationWrapper doCreateConsultation(String subscriptionID,String memberId,String callBackNumber,
                                                           String product,String IncomingNo,String paymentStatus,
                                                           String recordingId,String patientComplaint,String PaymentTransactionID)
    {
        //Subscriptions__c subs=[SELECT id,Status__c FROM Subscriptions__c WHERE ID=:subscriptionID];
        
        ConsultationWrapper consultWrapp=new ConsultationWrapper();
        Open_Consultants__c openConsult=new Open_Consultants__c();
        openConsult.CallBack_Number__c=callBackNumber;
        openConsult.Subscription__c =subscriptionID;
        openConsult.Products__c=product;
        openConsult.Member__c=memberId;
        openConsult.Incoming_Number__c=IncomingNo;
        openConsult.Payment_Status__c= paymentStatus;
        openConsult.Recording_ID__c=recordingId;
        openConsult.Problem_History__c=patientComplaint;
        openConsult.Payment_transaction_id__c=PaymentTransactionID;
        
        
         insert openConsult;
        
         if(openConsult.id!=null){
             consultWrapp.consultationID=openConsult.id;
             consultWrapp.statusMsg='Consultation Created Successfully';
         }
         else{
            consultWrapp.statusMsg='Consultation was not Successfully';
         }
       /* }
       else{
           consultWrapp.statusMsg='Subscription was not active'; 
       }*/
        return consultWrapp;  
    }
    
     global class ConsultationWrapper{
       public string consultationID;
       public string statusMsg;
     }

}