CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>CallMDUserName__c</fullName>
        <label>CallMDUserName</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName__c&amp;&quot; &quot;&amp;LastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IVR_UI_Flow__c</fullName>
        <label>IVR/UI Flow</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Update Consultation</fullName>
                </value>
                <value>
                    <fullName>New Subscription</fullName>
                </value>
                <value>
                    <fullName>New Consultation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Pin__c</fullName>
        <label>Member Pin</label>
        <length>10</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Member_Type__c</fullName>
        <label>Member Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pin__c</fullName>
        <label>Pin</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRMemberSubcriptionStatus.cls
@RestResource(urlMapping='/v1/verifyMemberSubscriptionStatus/*')
global class CallMD_IVRMemberSubcriptionStatus {
    
    @HttpGet
    global static memberSubscriptionStatus doVerifyMemberPin(){
        
        RestRequest req=RestContext.request;
        RestResponse res=RestContext.response;
        
        memberSubscriptionStatus respMem=new memberSubscriptionStatus();
        
        string CallMDAccountNumber=req.params.get('CallMDAccountNumber');
        string MemberPin=req.params.get('CallMDMemberPin');
        
        List<Member__c> memDetails;
        
        try{
            memDetails=[SELECT id,CallMDUserName__c,Cell_Phone__c,Member_Pin__c,Program_Status__c,Full_Name__c,State__c,
                               IVR_UI_Flow__c,Member_Type__c 
                               FROM Member__c 
                               WHERE CallMDUserName__c=:CallMDAccountNumber
                               AND Pin__c=:MemberPin];
            
            if(memDetails.size()==1){
                
                respMem.status='success';
                respMem.CallMDAccountNumber=memDetails[0].CallMDUserName__c;
                respMem.phoneNumber=memDetails[0].Cell_Phone__c;
                respMem.memberName=memDetails[0].Full_Name__c;
                respMem.memberID=memDetails[0].id;
                respMem.navigate=memDetails[0].IVR_UI_Flow__c;
                respMem.statusmsg='verified';
                respMem.state=memDetails[0].State__c;
                respMem.ProgramStatus=memDetails[0].Program_Status__c;
            } 
        }
        catch(exception e){}

        return respMem;
    }
    
    global class memberSubscriptionStatus{
        
        public string status;
        public string callMDAccountNumber;
        public string phoneNumber;
        public string statusmsg;
        public string subscriptionID;
        public string subscriptionStatus;
        public string providerID;
        public string providerName;
        public string programID;
        public string programName;
        public string memberName;
        public string memberID;
        public string state;
        Public string ProgramStatus;
        Public string navigate;
        public string memberType;
    }
    

}