CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>Consultation_Renewal__c</fullName>
        <label>Consultation Renewal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Copay_Amount__c</fullName>
        <formula>Program__r.Copay__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Copay Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Copay_Yes_No__c</fullName>
        <formula>TEXT(Program__r.Copay_Yes_No__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Copay Yes/No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscriptions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriptions</label>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Subscriptions (Child)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRUpdateSubscriptionConsultation.cls
@RestResource(urlMapping='/v1/updateSubscriptionConsultation')
global class CallMD_IVRUpdateSubscriptionConsultation {
    
    @HttPPost
    global static subscriptionRenewal doRenewal(String SubscriptionID){
        
        subscriptionRenewal subRenewal=new subscriptionRenewal();
        
        subscriptions__c sub=[SELECT id,Member__c,Copay_Yes_No__c,Copay_Amount__c,Consultation_Renewal__c 
                                                        FROM subscriptions__c 
                                                        WHERE ID=:SubscriptionID];
        
        sub.Consultation_Renewal__c=1;
        
        try{
        update sub;
      
        subRenewal.subscriptionID=sub.id;
        subRenewal.memberID=sub.Member__c;
        subRenewal.copayYesNo=sub.Copay_Yes_No__c;
        subRenewal.copayamount=sub.Copay_Amount__c;
        subRenewal.statusMsg='Renewal Sucessful';
        subRenewal.status='Success'; 
        }
        catch(exception e){
        subRenewal.subscriptionID=sub.id;
        subRenewal.memberID=sub.Member__c;
        subRenewal.copayYesNo=sub.Copay_Yes_No__c;
        subRenewal.copayamount=sub.Copay_Amount__c;
        subRenewal.statusMsg='Problem in renewal of subscription';
        subRenewal.status='Failed'; 
         
        }
        
        
        return subRenewal;
        
        
    }
    
    global class subscriptionRenewal{
        
        public string subscriptionID;
        public string memberID;
        public string statusMsg;
        public string status;
        public string copayYesNo;
        public Decimal copayamount;
    }

}