CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>CallBack_Number__c</fullName>
        <label>CallBack Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Consultation_Type__c</fullName>
        <label>Consultation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone consultation</fullName>
                </value>
                <value>
                    <fullName>Video Consultation</fullName>
                </value>
                <value>
                    <fullName>Chat Consultation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <label>Initiated By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PetMD</fullName>
                </value>
                <value>
                    <fullName>CallMD</fullName>
                </value>
                <value>
                    <fullName>EducationMD</fullName>
                </value>
                <value>
                    <fullName>TravelMD</fullName>
                </value>
                <value>
                    <fullName>FitMD</fullName>
                </value>
                <value>
                    <fullName>DentalMD</fullName>
                </value>
                <value>
                    <fullName>CorrectionsMD</fullName>
                </value>
                <value>
                    <fullName>HopeMD</fullName>
                </value>
                <value>
                    <fullName>DiagonosticsMD</fullName>
                </value>
                <value>
                    <fullName>PSYMD</fullName>
                </value>
                <value>
                    <fullName>SOSMD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMDIVR_Consultations.cls
@RestResource(urlMapping='/v1/initiateconsultation/*')
global class CallMDIVR_Consultations {
    
    @HttPPost
    global static responseConsultation CreateConsultation(String CallbackNumber,String ConsultationType,String InitiatedBy,String Member,String Product){
        
        RestRequest req=RestContext.request;
        RestResponse res=RestContext.response;
        
       responseConsultation respCon=new responseConsultation();
        Open_Consultants__c op=new Open_Consultants__c();
        
        try{
            op.CallBack_Number__c=CallbackNumber;
            op.Consultation_Type__c=ConsultationType;
            op.Initiated_By__c=InitiatedBy;
            op.Member__c=Member;
            op.Products__c=Product;
            
            insert op;
            
            if(op.id!=null){
                
                respCon.status='success';
                respCon.statusmsg='Created Successfully';
            }
            else{
                
                respCon.status='Failed';
                respCon.statusmsg='Created Failed';
                
            }
            
            
            
        }
        catch(Exception e){
            
        }
        return respCon;
    }
    
    global class responseConsultation{
        public string status;
        public string statusmsg;  
    }

}