CallMD/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Pharamcies__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Pharamcies</relationshipLabel>
        <relationshipName>Pharamcies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pharamcies</label>
    <nameField>
        <label>Pharamcy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharamcies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_PharmaciesExtCtrl.cls
public class CallMD_PharmaciesExtCtrl {

     Private String MemberID=ApexPages.CurrentPage().getParameters().get('mid');
     
     Public Pharamcies__c phar{get;set;}

    public CallMD_PharmaciesExtCtrl(ApexPages.StandardController controller) {
       phar=(Pharamcies__c)Controller.getRecord();
    }
    
    Public PageReference p;
    Public PageReference Save(){
      phar.Member__c=MemberID;
      insert phar;
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
    }
    
    Public PageReference Cancel(){
    
      p=new PageReference('/apex/CallMD_Member');
      p.getParameters().put('id',MemberID);
      p.getParameters().put('mode','e');
      return p;
    }
}