CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateofBirth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packages__c</fullName>
        <label>Packages</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>ZipCode</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_d2cRegistration.cls
@RestResource(urlMapping='/v1/d2cregistration/*')
global class CallMD_d2cRegistration {
    
    @HttpPost
    global static reponseMember createMemberSubscription(requestMember reqMem){
        
        reponseMember resp = new reponseMember();
        Member__c  mem = new Member__c();
        mem.FirstName__c = reqMem.firstname;
        mem.LastName__c = reqMem.lastname;
        mem.Cell_Phone__c = reqMem.mobileno;
        mem.Email__c = reqMem.email;
        mem.DateofBirth__c = reqMem.dob;
        mem.Gender__c = reqMem.gender;
        mem.City__c = reqMem.city;
        mem.State__c = reqMem.state;
        mem.ZipCode__c = reqMem.zipcode;
        mem.Packages__c = reqMem.packages;
    
        try{
        insert mem;
         if(mem.id!=null){ 
            resp.status='successful';
            resp.statusMsg='Created Successfully';
         }
         else{
            resp.status='Failed';
            resp.statusMsg='Not Created Successfully';
         }
        }
        catch(exception e){}
        
        return resp;
      }

global class requestMember{
    
    public string firstname;
    public string lastname;
    public string mobileno;
    public string email;
    public date dob;
    public string gender;
    public string city;
    public string state;
    public string zipcode;
    public string packages;     
}
    
 global class reponseMember{    
    public string status;
    public string statusMsg;            
  }
    
}