CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>CallMDUserName__c</fullName>
        <label>CallMDUserName</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Confirm_Member_Pin__c</fullName>
        <label>Confirm Member Pin</label>
        <length>10</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>DateofBirth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Pin__c</fullName>
        <label>Member Pin</label>
        <length>10</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Pin__c</fullName>
        <label>Pin</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isMemberPin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMemberPin</label>
        <type>Checkbox</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMDSetupCtrl.cls
public class CallMDSetupCtrl {

  Public Member__c memData;
  
  Private String MemberId=ApexPages.CurrentPage().getParameters().get('mid');
  
  Public CallMDSetupCtrl(){
  
     memData=new Member__c();
  }
  
  
  Public Member__c getMemDetails(){
  
  /* if(MemberId!=NULL){
    memData=[SELECT FirstName__c,LastName__c,DateofBirth__c,Cell_Phone__c,State__c 
                    FROM Member__c];
                    
  } */
  
  try{
  if(MemberID!=NULL){
  
    memData=[SELECT id,FirstName__c,LastName__c,DateofBirth__c,Cell_Phone__c,State__c,CallMDUserName__c,Name,isMemberPin__c,Email__c,
                    Member_Pin__c,Confirm_Member_Pin__c,Pin__c  
                    FROM Member__c WHERE ID=:MemberId];
  }
    }
    catch(Exception e){
    
    }
   
    return memData;
  
  }
  
  
  
  Public PageReference p;
  
  Public PageReference ConfirmMember(){
  
  try{
   memData=[SELECT id,Name,FirstName__c,LastName__c,DateofBirth__c,Cell_Phone__c,State__c,CallMDUserName__c 
                    FROM Member__c
                    WHERE FirstName__c=:memData.FirstName__c AND LastName__c=:memData.LastName__c 
                    AND DateofBirth__c=:memData.DateofBirth__c AND (Cell_Phone__c=:memData.Cell_Phone__c
                    OR State__c=:memData.State__c)];
   if(memData!=NULL){
    
    p=new PageReference('/apex/CallMDSetupConfirmPassword');
    p.getParameters().put('mid',memData.id);
    p.setRedirect(true);
   }
  }  
 
  Catch(Exception e){
    memData.Status__c='Active';
    memData.Pin__c=memData.Confirm_Member_Pin__c;
     insert memData;
     p=new PageReference('/apex/CallMDSetupConfirmPassword');
    p.getParameters().put('mid',memData.id);
    p.setRedirect(true);
     
   }
   
   
   return p;
  }
  
  Public PageReference Confirm(){
  
   try{
   if(memData!=NULL){
    memData.isMemberPin__c=true;
    memData.Pin__c=memData.Confirm_Member_Pin__c;
    update memData;
    p=new PageReference('/apex/CallMDSetupThankYou');
    p.getParameters().put('mid',memData.id);
    p.setRedirect(true);
   }
   }
   catch(Exception e){
   
   }
   
   return p;
  
    
  }

}