CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateofBirth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>ZipCode</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRMemberRegistration.cls
@RestResource(urlMapping='/v1/MemberRegistration/*')
global class CallMD_IVRMemberRegistration {
    
    @HttPPost
    global static registrationResponse memberRegistration(string firstname,string lastname,string cellphone,string city,string email,string gender,string zipcode,String DateOfBirth){
        registrationResponse res=new registrationResponse();
            
        Member__c mem=new Member__c();
        mem.FirstName__c=firstname;
        mem.LastName__c=lastname;
        mem.Cell_Phone__c=cellphone;
        mem.DateofBirth__c=Date.Parse(DateOfBirth);
        mem.City__c=city;
        mem.Email__c=email;
        mem.Gender__c=gender;
        mem.ZipCode__c=zipcode;
       
        insert mem;
        if(mem.id!=null){
        res.statusmsg='success';
        res.memberId=mem.id;
        }
        else{
          res.statusmsg='failure';   
        }
        return res;
        
    }
    
    global class registrationResponse{
        
       public string statusmsg;
       public string memberId;
    }

}