CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName__c&amp;&quot; &quot;&amp;LastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>American Independent Business Coalition</fullName>
                </value>
                <value>
                    <fullName>USHealth</fullName>
                </value>
                <value>
                    <fullName>USHealth Group</fullName>
                </value>
                <value>
                    <fullName>Benefit Services of America</fullName>
                </value>
                <value>
                    <fullName>OnCall Doctor</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Annual</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Monthly</fullName>
                </value>
                <value>
                    <fullName>Call BAA</fullName>
                </value>
                <value>
                    <fullName>CallMD Complimentary</fullName>
                </value>
                <value>
                    <fullName>CallMD One Time Consultation</fullName>
                </value>
                <value>
                    <fullName>Doctors</fullName>
                </value>
                <value>
                    <fullName>Family Care</fullName>
                </value>
                <value>
                    <fullName>Visionary</fullName>
                </value>
                <value>
                    <fullName>CallMD Sample</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>American Health Advantage True Care Discount Medical</fullName>
                </value>
                <value>
                    <fullName>American Seniors Association Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Benefit Services Of America-Test</fullName>
                </value>
                <value>
                    <fullName>CiProduct</fullName>
                </value>
                <value>
                    <fullName>Health Insurance Innovations-Extra Care Packag</fullName>
                </value>
                <value>
                    <fullName>Med Shield Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Southwest Advantage discount Plan</fullName>
                </value>
                <value>
                    <fullName>USH-PADD</fullName>
                </value>
                <value>
                    <fullName>Wellness Sheild-CallMD,Labs And Imaging</fullName>
                </value>
                <value>
                    <fullName>Wellness Shield-CallMD</fullName>
                </value>
                <value>
                    <fullName>CareExpress</fullName>
                </value>
                <value>
                    <fullName>Colonial Life</fullName>
                </value>
                <value>
                    <fullName>EnergyPlus</fullName>
                </value>
                <value>
                    <fullName>GlobalLife</fullName>
                </value>
                <value>
                    <fullName>LifeStyle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Programs__c.object
<CustomObject>
    <fields>
        <fullName>Copay__c</fullName>
        <label>Copay Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_of_Consultations__c</fullName>
        <label>No of Consultations</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <label>Pricing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <displayFormat>PROGID#{00000}</displayFormat>
        <label>Program ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Providers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Providers</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipName>Provider</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Programs / Packages</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs / Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Providers__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Providers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>B2B_D2C__c</fullName>
        <formula>TEXT( Program__r.Program_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>B2B/D2C</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copay_Amount__c</fullName>
        <formula>Program__r.Copay__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Copay Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <formula>Program__r.Pricing__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remaining_Consultation__c</fullName>
        <formula>IF(B2B_D2C__c==&apos;D2C&apos;
,IF(ISPICKVAL(Subscription_Type__c,&quot;New&quot;),(Total_Consultation_To_Do__c - Total_Consultations_Done__c),IF(ISPICKVAL(Subscription_Type__c,&quot;Renewal&quot;),Consultation_Renewal__c,0)),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Consultation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(B2B_D2C_Ref__c ==&apos;D2C&apos;,IF(AND(ISPICKVAL(Subscription_Type__c,&quot;New&quot;),ISPICKVAL(Payment__c ,&quot;Successful&quot;),End_Date__c&gt;=TODAY(),Remaining_Consultation__c&gt;=1),&apos;Active&apos;,
IF(AND(ISPICKVAL(Subscription_Type__c,&quot;Renewal&quot;),End_Date__c&gt;=TODAY(),Consultation_Renewal__c &gt;=1),&apos;Active&apos;,&apos;Expired&apos;)),IF(AND(B2B_D2C_Ref__c ==&apos;B2B&apos;,End_Date__c&gt;=TODAY()),&apos;Active&apos;,&apos;Expired&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriptions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriptions</label>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Subscriptions (Child)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Consultation_To_Do__c</fullName>
        <formula>IF(B2B_D2C__c==&apos;D2C&apos;,Program__r.No_of_Consultations__c +  Program__r.Free_Consultations__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Consultation To Do</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Consultations_Done__c</fullName>
        <label>Total Consultations Done</label>
        <summaryForeignKey>Open_Consultants__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRProviderConsultCharge.cls
@RestResource(urlMapping='/v1/CallMD_IVRProviderConsultCharge/*')
global class CallMD_IVRProviderConsultCharge {
    
    @HttPGet
    global static List<ConsultationWrapper> doGetConsultationCharge(){
        
        RestRequest req=RestContext.request;
        
        //Integer offset=integer.valueOf(req.params.get('start'));
        //Integer limits=integer.valueOf(req.params.get('end'));
         
      List<ConsultationWrapper> cw=new List<ConsultationWrapper>();
        
      //string query='SELECT Member__r.Full_Name__c,Program__r.Program_ID__c,Program__r.Name,Package__r.No_of_Consultations__c,Package__r.Pricing__c,Package__r.Copay__c,Package__r.Copay__c,Package__r.Remaining_Consultation__c FROM Subscriptions__c WHERE Status__c=\'Active\'';
       
       string query='SELECT Member__r.Full_Name__c,Program__r.Program_ID__c,Program__r.Name,Provider__r.Name,B2B_D2C__c,Pricing__c, Remaining_Consultation__c, Total_Consultations_Done__c,Total_Consultation_To_Do__c,Status__c, Start_Date__c, End_Date__c,Copay_Amount__c FROM Subscriptions__c WHERE Status__c=\'Active\'';
        
       List<Subscriptions__c> subList=Database.query(query);
        
        for(Subscriptions__c sub:subList){
           ConsultationWrapper c=new ConsultationWrapper(sub.Member__r.Full_Name__c,sub.Program__r.Program_ID__c,
                                                         sub.Program__r.Name,sub.Total_Consultations_Done__c,
                                                         sub.Remaining_Consultation__c,
                                                         sub.Pricing__c,sub.Copay_Amount__c);         
            cw.add(c);
        }
        return cw;
    }
    
    global class ConsultationWrapper{
        
       public string MemberName;
       public string ProgramID;
       Public String ProgramName;
       Public Decimal NoOfConsulatationsUsed;
       Public Decimal NoOfConsulatationsOwed;
       Public Decimal SubscriptionFee;
       Public Decimal CopayAmount;
        
        public ConsultationWrapper(string MemberName,string ProgramID,String ProgramName,Decimal NoOfConsulatationsUsed,Decimal NoOfConsulatationsOwed,Decimal Amount,Decimal CopayAmount){
            
            this.MemberName=MemberName;
            this.ProgramID=ProgramID;
            this.ProgramName=ProgramName;
            this.NoOfConsulatationsUsed=NoOfConsulatationsUsed;
            this.NoOfConsulatationsOwed=NoOfConsulatationsOwed;
            this.SubscriptionFee=Amount;
            this.CopayAmount=CopayAmount;
        }
   
    }
    

}