CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>B2B_Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>B2B Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D2C</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>American Independent Business Coalition</fullName>
                </value>
                <value>
                    <fullName>USHealth</fullName>
                </value>
                <value>
                    <fullName>USHealth Group</fullName>
                </value>
                <value>
                    <fullName>Benefit Services of America</fullName>
                </value>
                <value>
                    <fullName>OnCall Doctor</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Annual</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Monthly</fullName>
                </value>
                <value>
                    <fullName>Call BAA</fullName>
                </value>
                <value>
                    <fullName>CallMD Complimentary</fullName>
                </value>
                <value>
                    <fullName>CallMD One Time Consultation</fullName>
                </value>
                <value>
                    <fullName>Doctors</fullName>
                </value>
                <value>
                    <fullName>Family Care</fullName>
                </value>
                <value>
                    <fullName>Visionary</fullName>
                </value>
                <value>
                    <fullName>CallMD Sample</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>American Health Advantage True Care Discount Medical</fullName>
                </value>
                <value>
                    <fullName>American Seniors Association Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Benefit Services Of America-Test</fullName>
                </value>
                <value>
                    <fullName>CiProduct</fullName>
                </value>
                <value>
                    <fullName>Health Insurance Innovations-Extra Care Packag</fullName>
                </value>
                <value>
                    <fullName>Med Shield Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Southwest Advantage discount Plan</fullName>
                </value>
                <value>
                    <fullName>USH-PADD</fullName>
                </value>
                <value>
                    <fullName>Wellness Sheild-CallMD,Labs And Imaging</fullName>
                </value>
                <value>
                    <fullName>Wellness Shield-CallMD</fullName>
                </value>
                <value>
                    <fullName>CareExpress</fullName>
                </value>
                <value>
                    <fullName>Colonial Life</fullName>
                </value>
                <value>
                    <fullName>EnergyPlus</fullName>
                </value>
                <value>
                    <fullName>GlobalLife</fullName>
                </value>
                <value>
                    <fullName>LifeStyle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <label>Programs</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>B2B_D2C__c</fullName>
        <label>B2B/D2C</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>D2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Open Consultants</relationshipLabel>
        <relationshipName>Open_Consultants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Subscriptions__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Open Consultation</relationshipLabel>
        <relationshipName>Subscription</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Programs__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D2C</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Providers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Providers</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipName>Provider</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programs / Packages</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs / Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Providers__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>D2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Providers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>B2B_D2C__c</fullName>
        <formula>TEXT( Program__r.Program_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>B2B/D2C</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_B2BUtilizationReport.cls
public class CallMD_B2BUtilizationReport {

  public String programValue { get; set; }
    
  public map<id,string> mapProgramName{get;set;}
  
  public map<id,List<id>> mapProgProvName{get;set;}
  
  public map<id,string> mapProviderName{get;set;}
  
  Public List<Providers__c> provList;
  
  public string providerValue{get;set;}
  
  Public List<selectOption> providerOpt{get;set;}
  
  public List<Programs__c> progList;
  
  public List<Providers__c> provList2;
  
  public map<String,Double> mapFinal{get;set;}
  
  Public Date StartDate{get;set;}
  
  Public Date EndDate{get;set;}
    
  public CallMD_B2BUtilizationReport(){
  
       provList=[SELECT id,Name FROM Providers__c WHERE Customer_Type__c='B2B' ORDER BY Name];
       System.debug('Providers List:: '+provList);
       
       providerOpt=new List<selectOption>();
       
       for(providers__c p:provList){
         
         providerOpt.add(new selectOption(p.id,p.name));
       }
  }
  
  public List<selectOption> opt;
  
  Public List<selectOption> getProgramOption(){
  
    opt=new List<selectOption>();
     
     List<Programs__c> progList=[SELECT id,Name FROM Programs__c WHERE Program_Type__c='B2B'];
     
     for(Programs__c p : progList){
     
       opt.add(new selectOption(p.id,p.name));
     } 
   return opt;
  }
  
  
  public void change(){
 
  }
  
  
  public void CreateReport(){
  
    mapFinal=new map<string,Double>();
        
      provList2=[SELECT id,Name FROM Providers__c WHERE Customer_Type__c='B2B' AND ID=:providerValue];
      
      Set<Id> provIds=new Set<Id>();
      
      mapProviderName=new map<id,string>();
      
      for(Providers__c p:provList2){
          provIds.add(p.id);
          mapProviderName.put(p.id,p.name);
      }
      system.debug('Provider IDs:: '+provIds);
      
      system.debug('Provider Name:: '+mapProviderName);
      
      progList=[SELECT id,Name,Providers__c FROM Programs__c WHERE Providers__c IN:provIds AND ID=:programValue];
      System.debug('Program List:: '+progList);
      
      Set<Id> progIds=new Set<Id>();
      
      mapProgramName=new map<id,string>();
      
      mapProgProvName=new map<id,List<id>>();
      
      for(Programs__c p:progList){
          progIds.add(p.id);  
          mapProgramName.put(p.id,p.name); 
          
         if(!mapProgProvName.containsKey(p.Providers__c)){
            mapProgProvName.put(p.Providers__c,new List<Id>{p.id});
         }
         else{
           mapProgProvName.get(p.Providers__c).add(p.id);
         }
          
      }
      system.debug('Program Ids:: '+progIds);
      
      map<object,object> mapProgramConsultCount=new map<object,object>();
      
      AggregateResult[] arList=[SELECT Count(Subscription__r.Program__c),Program__c FROM Open_Consultants__c
                                WHERE B2B_D2C__c='B2B' AND (CreatedDate >=:StartDate AND CreatedDate <=:EndDate) GROUP BY Program__c  ];
      for(AggregateResult ar:arList){
          
          system.debug('PROG Count - Consultations:: '+ar.get('expr0')); 
          system.debug('Program ID:: '+ar.get('Program__c'));
          mapProgramConsultCount.put(ar.get('Program__c'),ar.get('expr0'));           
      }
      system.debug('Programs Count:: '+mapProgramConsultCount);
      
      map<object,object> mapProgramMemberCount=new map<object,object>();
      
      AggregateResult[] arList2=[SELECT count(id),B2B_Programs__c FROM Member__c WHERE Customer_Type__c='B2B' AND 
                                 B2B_Programs__c!=NULL 
                                 AND B2B_Programs__c IN:progIds AND (CreatedDate >=:StartDate AND CreatedDate <=:EndDate)
                                 GROUP BY B2B_Programs__c];
      
      for(AggregateResult ar:arList2){
          
          system.debug('Program ID:: '+ar.get('B2B_Programs__c'));
          system.debug('Member Count:: '+ar.get('expr0'));
          mapProgramMemberCount.put(ar.get('B2B_Programs__c'),ar.get('expr0'));
      }
      system.debug('Program Member Count:: '+mapProgramMemberCount);
     
      for(ID prog:progIds){
          
          Double d=double.ValueOf(mapProgramMemberCount.get(prog))/double.ValueOf(mapProgramConsultCount.get(prog))*100;
          system.debug(d);
          mapFinal.put(prog,d);  
          
      }
      system.debug('Program Utilization:: '+mapFinal);   
  
  
  }
  
  public pageReference generatePdf(){
    return page.CallMD_UtilizationReportPdf;
  }
    
  
}