CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>CallMDUserName__c</fullName>
        <label>CallMDUserName</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName__c&amp;&quot; &quot;&amp;LastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Pin__c</fullName>
        <label>Member Pin</label>
        <length>10</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Pin__c</fullName>
        <label>Pin</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>American Independent Business Coalition</fullName>
                </value>
                <value>
                    <fullName>USHealth</fullName>
                </value>
                <value>
                    <fullName>USHealth Group</fullName>
                </value>
                <value>
                    <fullName>Benefit Services of America</fullName>
                </value>
                <value>
                    <fullName>OnCall Doctor</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Annual</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Monthly</fullName>
                </value>
                <value>
                    <fullName>Call BAA</fullName>
                </value>
                <value>
                    <fullName>CallMD Complimentary</fullName>
                </value>
                <value>
                    <fullName>CallMD One Time Consultation</fullName>
                </value>
                <value>
                    <fullName>Doctors</fullName>
                </value>
                <value>
                    <fullName>Family Care</fullName>
                </value>
                <value>
                    <fullName>Visionary</fullName>
                </value>
                <value>
                    <fullName>CallMD Sample</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>American Health Advantage True Care Discount Medical</fullName>
                </value>
                <value>
                    <fullName>American Seniors Association Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Benefit Services Of America-Test</fullName>
                </value>
                <value>
                    <fullName>CiProduct</fullName>
                </value>
                <value>
                    <fullName>Health Insurance Innovations-Extra Care Packag</fullName>
                </value>
                <value>
                    <fullName>Med Shield Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Southwest Advantage discount Plan</fullName>
                </value>
                <value>
                    <fullName>USH-PADD</fullName>
                </value>
                <value>
                    <fullName>Wellness Sheild-CallMD,Labs And Imaging</fullName>
                </value>
                <value>
                    <fullName>Wellness Shield-CallMD</fullName>
                </value>
                <value>
                    <fullName>CareExpress</fullName>
                </value>
                <value>
                    <fullName>Colonial Life</fullName>
                </value>
                <value>
                    <fullName>EnergyPlus</fullName>
                </value>
                <value>
                    <fullName>GlobalLife</fullName>
                </value>
                <value>
                    <fullName>LifeStyle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Programs__c.object
<CustomObject>
    <fields>
        <fullName>Description_content__c</fullName>
        <label>Description_content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <label>Pricing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CallMD</fullName>
                </value>
                <value>
                    <fullName>PetMD</fullName>
                </value>
                <value>
                    <fullName>Dental MD</fullName>
                </value>
                <value>
                    <fullName>EducationMD</fullName>
                </value>
                <value>
                    <fullName>Travel MD</fullName>
                </value>
                <value>
                    <fullName>Fit MD</fullName>
                </value>
                <value>
                    <fullName>CorrectionsMD</fullName>
                </value>
                <value>
                    <fullName>HopeMD</fullName>
                </value>
                <value>
                    <fullName>PSYMD</fullName>
                </value>
                <value>
                    <fullName>SOSMD</fullName>
                </value>
                <value>
                    <fullName>DiagonosticsMD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <label>Program Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <formula>Providers__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_content__c</fullName>
        <label>Title_content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>large_image_url__c</fullName>
        <label>large_image_url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>small_image_url__c</fullName>
        <label>small_image_url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Programs / Packages</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs / Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>Copay_Amount__c</fullName>
        <formula>Program__r.Copay__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Copay Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <formula>Program__r.Pricing__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <formula>Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <formula>Provider__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(B2B_D2C_Ref__c ==&apos;D2C&apos;,IF(AND(ISPICKVAL(Subscription_Type__c,&quot;New&quot;),ISPICKVAL(Payment__c ,&quot;Successful&quot;),End_Date__c&gt;=TODAY(),Remaining_Consultation__c&gt;=1),&apos;Active&apos;,
IF(AND(ISPICKVAL(Subscription_Type__c,&quot;Renewal&quot;),End_Date__c&gt;=TODAY(),Consultation_Renewal__c &gt;=1),&apos;Active&apos;,&apos;Expired&apos;)),IF(AND(B2B_D2C_Ref__c ==&apos;B2B&apos;,End_Date__c&gt;=TODAY()),&apos;Active&apos;,&apos;Expired&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriptions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriptions</label>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Subscriptions (Child)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Consultation_To_Do__c</fullName>
        <formula>IF(B2B_D2C__c==&apos;D2C&apos;,Program__r.No_of_Consultations__c +  Program__r.Free_Consultations__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Consultation To Do</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Consultations_Done__c</fullName>
        <label>Total Consultations Done</label>
        <summaryForeignKey>Open_Consultants__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_UserMobileLogin.cls
@RestResource(urlMapping='/v1/verifymobilepin/*')
global class CallMD_UserMobileLogin {
    
    @HttpGet
    global static responseMemberPin doVerifyMemPin(){
        
        RestRequest req=RestContext.request;
        RestResponse res=RestContext.response;
        
        responseMemberPin respMem=new responseMemberPin();
        List<responseSubscription> responseSubList=new List<responseSubscription>();
        
        string UserAccess=req.params.get('UserAccess');
        string MemberPin=req.params.get('CallMDMemberPin');
        List<Member__c> memDetails;
        
        try{
        
            memDetails=[SELECT id,CallMDUserName__c,Cell_Phone__c,Email__c,Member_Pin__c,Program_Status__c   
                               FROM Member__c 
                               WHERE (CallMDUserName__c=:UserAccess OR Cell_Phone__c=:UserAccess OR Email__c=:UserAccess)
                               AND Pin__c=:MemberPin];
            
            if(memDetails.size()==1){
                
                respMem.status='success';
                respMem.UserAccess=memDetails[0].CallMDUserName__c;
                respMem.CallMDAccountNumber=memDetails[0].CallMDUserName__c;
                respMem.phoneNumber=memDetails[0].Cell_Phone__c;
                respMem.MemberId=memDetails[0].id;
                respMem.statusmsg='verified';
                
                if(memDetails[0].Program_Status__c=='Active'){
                    
                    List<Subscriptions__c> subList=[SELECT id,Member__c,Member__r.Full_Name__c,Program__c,Program__r.Product__c,Program_Name__c,Provider__c,
                                                 Provider_Name__c,Status__c,Total_Consultations_Done__c,Total_Consultation_To_Do__c,Pricing__c,Copay_Amount__c,  
                                                 Program__r.Description_content__c,Program__r.Title_content__c,Program__r.small_image_url__c,Program__r.large_image_url__c  
                                                 FROM Subscriptions__c 
                                                 WHERE Member__c=:memDetails[0].id];
                
                    
                    if(!subList.isEmpty()){  
                         for(Subscriptions__c sub:subList){
                          responseSubscription respSub=new responseSubscription();
                             respSub.subscriptionID=sub.id;
                             respSub.subscriptionStatus=sub.Status__c;
                             respSub.providerID=sub.Provider__c;
                             respSub.providerName=sub.Provider_Name__c;
                             respSub.programID=sub.Program__c;
                             respSub.programName=sub.Program_Name__c;
                             respSub.Amount=sub.Pricing__c;
                             respSub.consultationUsed =sub.Total_Consultations_Done__c;
                             respSub.consultationOwed =sub.Total_Consultation_To_Do__c;
                             respSub.CopayAmount=sub.Copay_Amount__c;
                             respSub.title=sub.Program__r.Product__c;
                             respSub.small_image_url=sub.Program__r.small_image_url__c;    
                             respSub.large_image_url=sub.Program__r.large_image_url__c;
                             respSub.title_content=sub.Program__r.Title_content__c;
                             respSub.description_content=sub.Program__r.Description_content__c;
                             responseSubList.add(respSub);
                         }
                      }
                        respMem.subscriptions=responseSubList;
                        system.debug('Subscriptions:: '+responseSubList);
                }
            }
            else{
                respMem.status='Failure';
                respMem.UserAccess=UserAccess;
                respMem.statusmsg='Not Verified';
            }
        }
        catch(exception e){}
        
        return respMem;
  
    }
    
   global class responseMemberPin{
        public string status;
        public string statusmsg; 
        public string callMDAccountNumber;
        public string UserAccess;
        public string memberName;
        public string MemberId;
        public string phoneNumber; 
        Public List<responseSubscription> subscriptions;
    }
   
    global class responseSubscription{
        
        public string subscriptionID;
        public string subscriptionStatus;
        public Double Amount;
        public string providerID;
        public string providerName;
        public string programID;
        public string programName;
        public double consultationUsed;
        public double consultationOwed; 
        public double copayAmount;
        public string title;
        public string small_image_url;
        public string large_image_url;
        public string title_content;
        public string description_content;
       
    }

}