CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>American Independent Business Coalition</fullName>
                </value>
                <value>
                    <fullName>USHealth</fullName>
                </value>
                <value>
                    <fullName>USHealth Group</fullName>
                </value>
                <value>
                    <fullName>Benefit Services of America</fullName>
                </value>
                <value>
                    <fullName>OnCall Doctor</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Annual</fullName>
                </value>
                <value>
                    <fullName>CallMD 24/7 Family Monthly</fullName>
                </value>
                <value>
                    <fullName>Call BAA</fullName>
                </value>
                <value>
                    <fullName>CallMD Complimentary</fullName>
                </value>
                <value>
                    <fullName>CallMD One Time Consultation</fullName>
                </value>
                <value>
                    <fullName>Doctors</fullName>
                </value>
                <value>
                    <fullName>Family Care</fullName>
                </value>
                <value>
                    <fullName>Visionary</fullName>
                </value>
                <value>
                    <fullName>CallMD Sample</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>American Health Advantage True Care Discount Medical</fullName>
                </value>
                <value>
                    <fullName>American Seniors Association Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Benefit Services Of America-Test</fullName>
                </value>
                <value>
                    <fullName>CiProduct</fullName>
                </value>
                <value>
                    <fullName>Health Insurance Innovations-Extra Care Packag</fullName>
                </value>
                <value>
                    <fullName>Med Shield Discount Plan</fullName>
                </value>
                <value>
                    <fullName>Southwest Advantage discount Plan</fullName>
                </value>
                <value>
                    <fullName>USH-PADD</fullName>
                </value>
                <value>
                    <fullName>Wellness Sheild-CallMD,Labs And Imaging</fullName>
                </value>
                <value>
                    <fullName>Wellness Shield-CallMD</fullName>
                </value>
                <value>
                    <fullName>CareExpress</fullName>
                </value>
                <value>
                    <fullName>Colonial Life</fullName>
                </value>
                <value>
                    <fullName>EnergyPlus</fullName>
                </value>
                <value>
                    <fullName>GlobalLife</fullName>
                </value>
                <value>
                    <fullName>LifeStyle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <label>Programs</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Programs__c.object
<CustomObject>
    <fields>
        <fullName>Consultations_Done_Till_Now__c</fullName>
        <label>Consultations Done Till Now</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programs / Packages</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs / Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriptions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriptions</label>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Subscriptions (Child)</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Consultations_Completed_B2B__c</fullName>
        <label>Total Consultations Completed B2B</label>
        <summaryFilterItems>
            <field>Open_Consultants__c.B2B_D2C__c</field>
            <operation>equals</operation>
            <value>B2B</value>
        </summaryFilterItems>
        <summaryForeignKey>Open_Consultants__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/subscriptionMemberTriggerHandler.cls
public class subscriptionMemberTriggerHandler {
     
    public static void memberB2BUtilization(List<Subscriptions__c> subList){
        Set<id> programIds=new Set<Id>();
        Map<id,List<Subscriptions__c>> mapSubscription=new Map<id,List<Subscriptions__c>>();
        List<Member__c> memList=new List<Member__c>();
        map<id,Programs__c> mapProgramUpdate=new map<id,Programs__c>();
        map<id,Decimal> mapProgramConsultNo=new map<id,Decimal>();
        Decimal count=0; 
        
        for(Subscriptions__c sub:subList){
            programIds.add(sub.Program__c);
        }
        if(!programIds.isEmpty()){
            List<Subscriptions__c> lstSubscription=[SELECT id,Total_Consultations_Completed_B2B__c,Program__c  
                                                    FROM Subscriptions__c 
                                                    WHERE Program__c IN:programIds];
            
            for(Subscriptions__c sub:lstSubscription){
                
                count=count+sub.Total_Consultations_Completed_B2B__c;
                
                if(!mapProgramConsultNo.containsKey(sub.Program__c)){
                    mapProgramConsultNo.put(sub.Program__c,count);
                }
            }
            
            for(Subscriptions__c sub:subList){
                Programs__c p=new Programs__c();
                p.id=sub.Program__c;
                p.Consultations_Done_Till_Now__c=mapProgramConsultNo.get(sub.Program__c);
                mapProgramUpdate.put(sub.Program__c,p);
            }
            
            if(!mapProgramUpdate.isEmpty()){
                update mapProgramUpdate.values();
            } 
        }
    }

}