CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address Line1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR(TODAY()) - YEAR(DateofBirth__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CallMDUserName__c</fullName>
        <label>CallMDUserName</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D2C</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DateofBirth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName__c&amp;&quot; &quot;&amp;LastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Parent_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>ZipCode</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_MemberDependentCtrl.cls
public class CallMD_MemberDependentCtrl {

   Public string MemberID=ApexPages.CurrentPage().getParameters().get('mid');
   
   public string mode{get;set;}
   
   public Member__c memInfo{get;set;}

    public CallMD_MemberDependentCtrl(ApexPages.StandardController controller) {
    
     memInfo=(member__c)controller.getRecord();
    
      mode='e';

    }
    
    Public Member__c mem;
    
    Public Member__c getMemberDetails(){
    
     if(MemberID!=null){
      mem=[SELECT id,FirstName__c,LastName__c,DateofBirth__c,Age__c,
                          Gender__c,Address_Line1__c,City__c,State__c,Home_Phone__c,
                          Work_Phone__c,Cell_Phone__c,Height__c,Weight__c 
                          FROM Member__c
                          WHERE ID=:MemberID];
      }
      return mem;
    }
    
    Public List<Member__c> memList;
    
    public integer memSize{get;set;}
    
    Public List<Member__c> getMembersList(){
    
      if(memberID!=null){
      
        memList=[SELECT id,Name,FirstName__c,LastName__c,Parent_Member__r.Full_Name__c,Parent_Member__c,DateofBirth__c,
                         Customer_Type__c,City__c,State__c,ZipCode__c   
                         FROM Member__c WHERE Parent_Member__c=:MemberID];
        
        memSize=memList.size();
      }
      
      return memList;
    
    }
    
    public pageReference p;
    public pageReference save(){
    try{
      if(memInfo.CallMDUserName__c==null){
        memInfo.CallMDUserName__c.addError('Cannot be Empty and must be numeric...!');
      }
      else{
       memInfo.Parent_Member__c=MemberID;
       insert memInfo;
       if(memInfo.id!=null){
          p=new pageReference('/apex/CallMD_MemberDependent');
          p.getParameters().put('mid',MemberID);
          p.setRedirect(true);
         
       }
      }
     }
     catch(exception e){}
      return p;
    }
    
    

}