CallMD/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirm_Member_Pin__c</fullName>
        <label>Confirm Member Pin</label>
        <length>10</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Member_Pin__c</fullName>
        <label>Member Pin</label>
        <length>10</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRMemberResetPassword.cls
@RestResource(urlMapping='/v1/resetpassword/*')
global class CallMD_IVRMemberResetPassword {
    
    @HttPPost
    global static memberResponse MemberResetPassword(string memberid,string answer,string password){
        
        Member__c mem=[SELECT id,Answer__c,Confirm_Member_Pin__c,Member_Pin__c 
                                                   FROM Member__c 
                                                   WHERE id=:memberid];
        
        memberResponse resp=new memberResponse();
        
        if(mem.Answer__c==answer){
          mem.Member_Pin__c=password;
          mem.Confirm_Member_Pin__c=password;
          update mem;
          resp.statusMsg='Updated Successfully';
          resp.status='Success';
          resp.memberId=mem.id;   
        }
        else{
          resp.statusMsg='No Answer Matched';
          resp.status='Failed';
          resp.memberId=mem.id;
        }
        
        return resp;
        
    }
    
    
    global class memberResponse{
        
        public string statusMsg;
        public string status;
        public string memberId;
        
    }

}