CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>DoctorC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Open Consultation</relationshipLabel>
        <relationshipName>Open_Consultation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_IVRAssignDoctor.cls
@RestResource(urlMapping='/v1/assigndoctor/*')
global class CallMD_IVRAssignDoctor {
    
    @HttpPost
    global static responseDoctor AssignDoctor(string consultationid,string doctorid){
      
      responseDoctor resp=new responseDoctor();
      Open_Consultants__c openConsult=[SELECT id,DoctorC__c FROM Open_Consultants__c WHERE ID=:consultationid];
      openConsult.DoctorC__c=doctorid;
      update openConsult;
      
        if(openConsult.id!=null){
            resp.status='Success';
            resp.statusMsg='Assigned to Doctor Successfully';
        }
        else{
            resp.status='Failure';
            resp.statusMsg='Not Updated';
        }
        
      return resp;  
    }
    
    global class responseDoctor{
        
       public string status;
       public string statusMsg;
        
    }

}