CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Subscriptions__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscriptions__c</referenceTo>
        <relationshipLabel>Open Consultation</relationshipLabel>
        <relationshipName>Subscription</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/objects/Programs__c.object
<CustomObject>
    <fields>
        <fullName>Providers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Providers</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipName>Provider</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programs / Packages</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs / Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Providers__c.object
<CustomObject>
    <label>Providers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Subscriptions__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Subscriptions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_ConsultationReports.cls
public class CallMD_ConsultationReports {

   Public Map<string,List<ConsultationInfo>> mapConsult{get{
   
      Map<string,List<ConsultationInfo>> mapConsultInfo=new Map<string,List<ConsultationInfo>>();
      
      ConsultationInfo consult=new ConsultationInfo();
      
      List<String> providersLst=new List<String>{'CallMD'};
      
      List<Open_Consultants__c> lstOpenConsultation=[SELECT id,Subscription__r.Program__c,Subscription__r.Program__r.Name,
                                                            Subscription__r.Provider__c,Subscription__r.Provider__r.Name 
                                                            FROM Open_Consultants__c];
                                                            
      Map<string,List<Open_Consultants__c>> mapConsultations=new Map<string,List<Open_Consultants__c>>();
         
      for(Open_Consultants__c openConsult:lstOpenConsultation){
        if(!mapConsultations.containsKey(openConsult.Subscription__r.Provider__c+'-'+openConsult.Subscription__r.Program__c)){
         mapConsultations.put(openConsult.Subscription__r.Provider__c+'-'+openConsult.Subscription__r.Program__c,
                                 new List<Open_Consultants__c>{openConsult});
         }
         else{
          mapConsultations.get(openConsult.Subscription__r.Provider__c+'-'+openConsult.Subscription__r.Program__c).add(openConsult);
         }
      } 
      
                                                          
                                                            
      
      List<ConsultationInfo> lstConsultInfo=new List<ConsultationInfo>();
      
      ConsultationInfo consInfo=new ConsultationInfo();
      consInfo.ProviderName='CallMD';
      consInfo.ProgramId='';
      consInfo.ProgramName='One Time';
      consInfo.NoOfConsultations=10;
      lstConsultInfo.add(consInfo);
       
      ConsultationInfo consInfo2=new ConsultationInfo();
      consInfo2.ProviderName='CallMD';
      consInfo2.ProgramId='';
      consInfo2.ProgramName='Family';
      consInfo2.NoOfConsultations=20;
      lstConsultInfo.add(consInfo2);
      
      ConsultationInfo consInfo3=new ConsultationInfo();
      consInfo3.ProviderName='CallMD';
      consInfo3.ProgramId='';
      consInfo3.ProgramName='Package-3 6 Months Subscription Plan';
      consInfo3.NoOfConsultations=30;
      lstConsultInfo.add(consInfo3);
      
      ConsultationInfo consInfo4=new ConsultationInfo();
      consInfo4.ProviderName='CallMD';
      consInfo4.ProgramId='';
      consInfo4.ProgramName='Package-4 12 Months Subscription Plan';
      consInfo4.NoOfConsultations=40;
      lstConsultInfo.add(consInfo4);
      
      
     
      mapConsultInfo.put('CallMD',lstConsultInfo);
  
      return mapConsultInfo;
   
   
   }set;}


   Public class ConsultationInfo{
   
     Public String ProgramName{get;set;}
     Public String ProgramId{get;set;}
     Public String ProviderName{get;set;}
     Public Integer NoOfConsultations{get;set;}
   
   
   }


}