CallMD/src/objects/Open_Consultants__c.object
<CustomObject>
    <fields>
        <fullName>CallBack_Number__c</fullName>
        <label>CallBack Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Consultation_Type__c</fullName>
        <label>Consultation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone consultation</fullName>
                </value>
                <value>
                    <fullName>Video Consultation</fullName>
                </value>
                <value>
                    <fullName>Chat Consultation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <label>Initiated By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pharmacy_Name_Phone__c</fullName>
        <label>Pharmacy Name + Phone:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PetMD</fullName>
                </value>
                <value>
                    <fullName>CallMD</fullName>
                </value>
                <value>
                    <fullName>EducationMD</fullName>
                </value>
                <value>
                    <fullName>TravelMD</fullName>
                </value>
                <value>
                    <fullName>FitMD</fullName>
                </value>
                <value>
                    <fullName>DentalMD</fullName>
                </value>
                <value>
                    <fullName>CorrectionsMD</fullName>
                </value>
                <value>
                    <fullName>HopeMD</fullName>
                </value>
                <value>
                    <fullName>DiagonosticsMD</fullName>
                </value>
                <value>
                    <fullName>PSYMD</fullName>
                </value>
                <value>
                    <fullName>SOSMD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Consultation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Open Consultants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Consultation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CallMD/src/classes/CallMD_OpenConsultationsCtrlTest.cls
@isTest
private class CallMD_OpenConsultationsCtrlTest {
    
    testMethod static void OpenConsultations(){
        
        CallMD_OpenConsultationsCtrl openConsult=new CallMD_OpenConsultationsCtrl();
        
        Open_Consultants__c op=new Open_Consultants__c ();
        op.Consultation_Type__c='Phone consultation';
        op.Initiated_By__c='Provider';
        op.CallBack_Number__c='(909) 909-9090';
        op.Pharmacy_Name_Phone__c='(809) 909-9090';
        op.Products__c='CallMD'; 
        insert op;
        
        Open_Consultants__c opc=[SELECT Consultation_Type__c,Initiated_By__c,CallBack_Number__c,Pharmacy_Name_Phone__c,Products__c
                                       FROM Open_Consultants__c
                                       WHERE id=:op.id];
        
        system.assertEquals('Phone consultation',opc.Consultation_Type__c);
        system.assertEquals('Provider',opc.Initiated_By__c);
        system.assertEquals('(909) 909-9090',opc.CallBack_Number__c);
        system.assertEquals('(809) 909-9090',opc.Pharmacy_Name_Phone__c);
        system.assertEquals('CallMD',opc.Products__c);
        
        openConsult.getOpenConsultList();
        openConsult.first();
        openConsult.last();
        openConsult.previous();
        openConsult.next();
        openConsult.getHasNext();
        openConsult.getHasPrevious();
    }

}