CallMD/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Programs__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address Line1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Contact Person</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copay_Yes_No__c</fullName>
        <label>Copay Yes/No</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Copay__c</fullName>
        <label>Copay Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deactivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deactivate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Free_Consultations__c</fullName>
        <label>Free Consultations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Consultations__c</fullName>
        <label>No of Consultations</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Program_Name__c</fullName>
        <formula>Programs__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Program  Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <label>Pricing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CallMD</fullName>
                </value>
                <value>
                    <fullName>PetMD</fullName>
                </value>
                <value>
                    <fullName>Dental MD</fullName>
                </value>
                <value>
                    <fullName>EducationMD</fullName>
                </value>
                <value>
                    <fullName>Travel MD</fullName>
                </value>
                <value>
                    <fullName>Fit MD</fullName>
                </value>
                <value>
                    <fullName>CorrectionsMD</fullName>
                </value>
                <value>
                    <fullName>HopeMD</fullName>
                </value>
                <value>
                    <fullName>PSYMD</fullName>
                </value>
                <value>
                    <fullName>SOSMD</fullName>
                </value>
                <value>
                    <fullName>DiagonosticsMD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <label>Program Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <formula>Providers__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Providers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Providers</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipName>Provider</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>Programs / Packages</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs / Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Providers__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address Line1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address_Line2__c</fullName>
        <label>Address Line2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Contact Person</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deactivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deactivate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <label>Home Page</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Dummy Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone1__c</fullName>
        <label>Phone1</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone2__c</fullName>
        <label>Phone2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Started_Date__c</fullName>
        <label>Started Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>ZipCode</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Providers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/ProviderCtrl.cls
public class ProviderCtrl {
    
    Public Providers__c prov{get;set;}
    Public string ProgramStatus {get;set;}
    Public String ProviderStatus {get;set;}
    Public String ProviderName{get;set;}
    Private string ProviderId;
    public List<Providers__c> providersList {get;set;}
    Public List<string> conditions = new List<string>();
    private integer totalRecs = 0;
    private integer OffsetSize = 0;
    private integer LimitSize= 10;
    public string filename{get;set;}
    public transient blob filebody{get;set;}
    
   
    
    public String mode{
    get{
        return ApexPages.CurrentPage().getParameters().get('mode');
    }set; }
    
    public ProviderCtrl(ApexPages.StandardController controller) {
        prov=(Providers__c)controller.getRecord();
        ProviderId=controller.getId();
        if(ProviderId!=null){
            Programs=[SELECT id,Name,Name__c,Programs__r.Program_Name__c,Program_Name__c,Program_Status__c,
                                 Pricing__c,Copay_Yes_No__c,Copay__c,No_of_Consultations__c, Free_Consultations__c,
                                 Product__c, Provider_Name__c,Parent_Program_Name__c,Providers__c
                                 FROM Programs__c 
                                 WHERE Providers__c=:ProviderId];
        }
    }
    
    Public pageReference p;
    Public pageReference Save(){
        try{
            insert prov;
            p=new PageReference('/apex/CallMD_Provider');
            p.getParameters().put('id',prov.id);
            p.getParameters().put('mode','s');
            p.setRedirect(true);
        }
        catch(exception e){
        }
        return p;
    }
    
    Public PageReference updateProv(){
        try{
            update prov;
            p=new PageReference('/apex/CallMD_Provider');
            p.getParameters().put('id',ProviderID);
            p.getParameters().put('mode','s');
            p.setRedirect(true);
        }
        catch(Exception e){}
        return p;
    }
    
    Public List<Programs__c> Programs;
    Public List<Programs__c> getProgramList(){
        return programs;
    }
    
    Public Void ChangeProgramStatus(){
        Programs=[SELECT id,Programs__r.Name,Name,Program_Status__c,No_of_Consultations__c,
                            Pricing__c,Copay_Yes_No__c,Copay__c, Providers__c,Free_Consultations__c,
                            Product__c,Provider_Name__c,Parent_Program_Name__c
                            FROM Programs__c 
                            WHERE Providers__c=:ProviderId AND Program_Status__c=:ProgramStatus];
    }
    
    Public PageReference NavigateToProvider(){
        p=new pageReference('/apex/CallMD_Provider');
        p.setRedirect(true);
        return p;
    }
    
    public void clear(){
        ProviderName='';
        ProviderStatus='';
        searchSobject();
    }
    
    Public pageReference Edit(){
        p=new PageReference('/apex/CallMD_Provider');
        p.getParameters().put('id',ProviderId);
        p.getParameters().put('mode','e');
        p.getParameters().put('retPageName','CallMD_Provider');
        p.setRedirect(true);
        return p;
    }
    
    Public pageReference cancel(){
        p=new PageReference('/apex/CallMD_Provider');
        p.getParameters().put('id',ProviderId);
        p.getParameters().put('mode','s');
        p.getParameters().put('retPageName','CallMD_Provider');
        p.setRedirect(true);
        return p;
    }
    
    public void upload(){
    
      Attachment att = new Attachment();
      att.Name=filename;
      att.body=filebody;
      att.parentId=ProviderId;
      insert att;
    
    }
    
    public List<Attachment> getDocList(){
    
    
      List<Attachment> attachList;
    
      if(string.isNotEmpty(providerId)){
      
         attachList = [SELECT id,Name FROM Attachment WHERE ParentId =: ProviderId];
      }
      
      return attachList;
    
    
    }
    
    
    public void searchSobject(){
        totalRecs = 0;
        OffsetSize = 0;
        if(providersList!=null && providersList.size()>0){
            ProvidersList=null;
        }
        
        searchSobjects(); 
        //conditions.clear();  
    }
    
    public Void searchSobjects(){
        
        if(providersList!= null && !providersList.isEmpty()){
            providersList.clear();
        }
        String strQuery ='SELECT id,Name,Name__c,Deactivate__c,Started_Date__c,Address_Line1__c,Address_Line2__c,City__c,State__c,ZipCode__c,Phone1__c,Phone2__c,Fax__c,Email__c,Contact_Person__c,Home_Page__c,Status__c FROM Providers__c';  
        if(ProviderName!=null && ProviderName!=''){
            conditions.add('Name Like \'%' +ProviderName +'%\' ');
        }
        if(ProviderStatus!=null && ProviderStatus!=''){
            conditions.add('Status__c Like \'%' +ProviderStatus +'%\' ');
        }
        if(conditions.size() > 0) {
            strQuery += '  WHERE ' + conditions[0];
            for (Integer i = 1; i < conditions.size(); i++)
                strQuery += '  OR ' + conditions[i];
        }
        if(totalRecs !=null && totalRecs ==0){
            List<Providers__c> accTemp = Database.query(strQuery);
            totalRecs = (accTemp !=null &&accTemp.size()>0)?accTemp.size():0;
        }
        strQuery += ' ORDER BY Name  ASC, CreatedDate DESC LIMIT :LimitSize OFFSET :OffsetSize';
        providersList =Database.query(strQuery);
    }
    public void first()
    {
        OffsetSize = 0;
        searchSobjects();
    }
    public void previous()
    {
        OffsetSize = (OffsetSize-LimitSize);
        searchSobjects();
    }
    public void next()
    {
        OffsetSize = OffsetSize + LimitSize;
        searchSobjects();
    }
    public void last()
    {
        OffsetSize = totalrecs - math.mod(totalRecs,LimitSize);
        searchSobjects();
    }
    public boolean getHasPrevious()
    {
        Boolean res1;
        if(OffsetSize == 0){
            
            res1=true;
        }
        return res1;
    }
    public boolean getHasNext()
    {
        Boolean res1;
        if((OffsetSize + LimitSize) > totalRecs){
            
            res1=true;
        }
        return res1;
    }
}