CallMD/src/objects/Programs__c.object
<CustomObject>
    <fields>
        <fullName>Copay_Yes_No__c</fullName>
        <label>Copay Yes/No</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Copay__c</fullName>
        <label>Copay Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Providers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Providers</label>
        <referenceTo>Providers__c</referenceTo>
        <relationshipName>Provider</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programs / Packages</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs / Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/objects/Providers__c.object
<CustomObject>
    <fields>
        <fullName>Programs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programs</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Providers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/ProgramsCtrl.cls
public class ProgramsCtrl {

   Public Programs__c prog{get;set;}
   
   Private String ProviderId=ApexPages.CurrentPage().getParameters().get('provid');
   
   Private String ProgramID=ApexPages.CurrentPage().getParameters().get('progid');
   
    public ProgramsCtrl(ApexPages.StandardController controller) {

        prog=(Programs__c)controller.getRecord();
    }
    
    Public PageReference p;
    
    Public PageReference Save(){
     
     try{
      prog.Providers__c=ProviderId;
      
      if(ProgramID!=''||ProgramID!=NULL){
    
       Prog.Programs__c=ProgramID;
      }
      if(prog.Copay_Yes_No__c=='Yes' && prog.Copay__c==null){
      
         prog.Copay__c.addError('Copay Amount Cannot be kept empty');
      
      }
      else if(prog.Copay_Yes_No__c =='No' && prog.Copay__c!=null){
         prog.Copay__c.addError('Copay Amount Cannot be filled if copay doesnt exist');
      
      }
      else{
      insert prog;
      p=new PageReference('/apex/CallMD_Provider');
      p.getParameters().put('id',ProviderId);
      p.getParameters().put('mode','s');
     }
     
      
     }
    catch(exception e){
    
    } 
    return p;  
   }
   
   Public PageReference UpdateProg(){
   
   try{
   
     update prog;
     
      p=new PageReference('/apex/CallMD_Provider');
      p.getParameters().put('id',ProviderId);
      p.getParameters().put('mode','e');
     
    }
    catch(Exception e){
    
    }
    return p;
   }

}