CallMD/src/objects/Providers__c.object
<CustomObject>
    <fields>
        <fullName>Logo_ID__c</fullName>
        <label>Logo ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Providers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/Logoctrl.cls
public class Logoctrl 
{
    public string LogoName{get;set;}
    public transient blob LogoBody{get;set;}
    private string recordID;
    
    public Logoctrl(ApexPages.StandardController controller) {
        recordID=controller.getID();
    }
    public pagereference upload(){
        Attachment att=new Attachment();
        att.Name=LogoName;
        att.Body=LogoBody;
        att.parentID=RecordID;
        insert att;
        Providers__c p=new Providers__c();
        p.id=recordid;
        p.Logo_ID__c=att.id;
        update p;
        return null;
    }
    
    
}