CallMD/src/objects/Providers__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Dummy Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Providers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CallMD/src/classes/LogoCtrl_Test.cls
@isTest
private class LogoCtrl_Test {
    
    testMethod static void Logo(){
        
        Providers__c p=new Providers__c();
        p.Name__c='Test Provider';
        insert p;
        ApexPages.StandardController sc=new  ApexPages.StandardController(p);
        Logoctrl l=new Logoctrl(sc);
        l.LogoName='Provider';
        l.LogoBody=Blob.valueOf('Testing');
        l.upload();
    }

}